// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Variant 2' | 'Variant 3' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * date?: string // Date
 * title?: string // Title
 * link ?: string // Link 
}} Props

 */
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:blog-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bsuhQ8eV4DgUA5hFYKlV/kXuh0W9wfT4lYbgv1zAi/HdU3c9dDU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/88qzwfAdEaELhKIsMcnP/ex8vP9VSA4wZfCLrngP6/Clb2Z6A0U.js
import { fontStore } from "unframer";
fontStore.loadWebFontsFromSelectors(["GF;Barlow-regular"]);
var fonts = [
	{
		family: "Barlow",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/Clb2Z6A0U:default",
			url: "https://fonts.gstatic.com/s/barlow/v12/7cHpv4kjgoGqM7EPC8E46HsxnA.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/barlow/v12/7cHpv4kjgoGqM7EPC8E46HsxnA.ttf",
		weight: "400",
	},
];
var css = [
	'.framer-SZJhJ .framer-styles-preset-1sb8f1f:not(.rich-text-wrapper), .framer-SZJhJ .framer-styles-preset-1sb8f1f.rich-text-wrapper p { --framer-font-family: "Barlow", "Barlow Placeholder", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; }',
];
var className = "framer-SZJhJ";

// /:https://framerusercontent.com/modules/iQzCddwwJ27CQVoKfINc/pUozo8wMep2BON4wKjTH/f9z7v91ro.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadWebFontsFromSelectors(["GF;Playfair Display-500"]);
var fonts2 = [
	{
		family: "Playfair Display",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/f9z7v91ro:default",
			url: "https://fonts.gstatic.com/s/playfairdisplay/v36/nuFvD-vYSZviVYUb_rj3ij__anPXJzDwcbmjWBN2PKd3vUDQZNLo_U2r.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/playfairdisplay/v36/nuFvD-vYSZviVYUb_rj3ij__anPXJzDwcbmjWBN2PKd3vUDQZNLo_U2r.ttf",
		weight: "500",
	},
];
var css2 = [
	'.framer-XAdu8 .framer-styles-preset-1pkgc8z:not(.rich-text-wrapper), .framer-XAdu8 .framer-styles-preset-1pkgc8z.rich-text-wrapper h4 { --framer-font-family: "Playfair Display", serif; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.015625em; --framer-line-height: 130%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 810px) { .framer-XAdu8 .framer-styles-preset-1pkgc8z:not(.rich-text-wrapper), .framer-XAdu8 .framer-styles-preset-1pkgc8z.rich-text-wrapper h4 { --framer-font-family: "Playfair Display", serif; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.015625em; --framer-line-height: 130%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-XAdu8 .framer-styles-preset-1pkgc8z:not(.rich-text-wrapper), .framer-XAdu8 .framer-styles-preset-1pkgc8z.rich-text-wrapper h4 { --framer-font-family: "Playfair Display", serif; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.015625em; --framer-line-height: 130%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className2 = "framer-XAdu8";

// /:https://framerusercontent.com/modules/NUrVxb9VkgG5ACdJYbAS/vrqcsYYfOCkazf47dWWz/LseYDyRFN.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadWebFontsFromSelectors([]);
var fonts3 = [];
var css3 = [
	'.framer-Q4Aob .framer-styles-preset-sijqht:not(.rich-text-wrapper), .framer-Q4Aob .framer-styles-preset-sijqht.rich-text-wrapper a { --framer-link-current-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b) /* {"name":"Neutral / 07"} */; --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b) /* {"name":"Neutral / 07"} */; --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-link-text-decoration: none; }',
];
var className3 = "framer-Q4Aob";

// /:https://framerusercontent.com/modules/bsuhQ8eV4DgUA5hFYKlV/kXuh0W9wfT4lYbgv1zAi/HdU3c9dDU.js
var cycleOrder = ["yXOQhTaw7", "RnbzNHxWd", "QE5tuIzyT"];
var serializationHash = "framer-7pj3m";
var variantClassNames = {
	QE5tuIzyT: "framer-v-eyhbr0",
	RnbzNHxWd: "framer-v-1wd7e3n",
	yXOQhTaw7: "framer-v-1l433sg",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 2": "RnbzNHxWd",
	"Variant 3": "QE5tuIzyT",
	Default: "yXOQhTaw7",
};
var getProps = ({ date, height, id, image, link, title, width, ...props }) => {
	return {
		...props,
		Jikq4K9FE: image ??
			props.Jikq4K9FE ?? {
				pixelHeight: 2e3,
				pixelWidth: 3e3,
				src: "https://framerusercontent.com/images/hLQUNN19E0OvmJl9cRFV0fA4nA.jpg?scale-down-to=512&width=3000&height=2000",
				srcSet:
					"https://framerusercontent.com/images/hLQUNN19E0OvmJl9cRFV0fA4nA.jpg?scale-down-to=512&width=3000&height=2000 512w,https://framerusercontent.com/images/hLQUNN19E0OvmJl9cRFV0fA4nA.jpg?scale-down-to=1024&width=3000&height=2000 1024w,https://framerusercontent.com/images/hLQUNN19E0OvmJl9cRFV0fA4nA.jpg?scale-down-to=2048&width=3000&height=2000 2048w,https://framerusercontent.com/images/hLQUNN19E0OvmJl9cRFV0fA4nA.jpg?width=3000&height=2000 3000w",
			},
		Kekq9f1i5: link ?? props.Kekq9f1i5,
		lyVKu539X: date ?? props.lyVKu539X ?? "August 28, 2023",
		QcaJUmNfx:
			title ?? props.QcaJUmNfx ?? "How to choose the best bedroom decor",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "yXOQhTaw7",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		Jikq4K9FE,
		lyVKu539X,
		QcaJUmNfx,
		Kekq9f1i5,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yXOQhTaw7",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1byseis = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("QE5tuIzyT");
	});
	const onMouseLeave1b68joz = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("yXOQhTaw7");
	});
	const sharedStyleClassNames = [className, className2, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1l433sg",
							className4,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"yXOQhTaw7"}
						onMouseEnter={onMouseEnter1byseis}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								QE5tuIzyT: {
									"data-framer-name": "Variant 3",
									onMouseLeave: onMouseLeave1b68joz,
								},
								RnbzNHxWd: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-11z93t5"}
							data-framer-name={"Blog Image"}
							layoutDependency={layoutDependency}
							layoutId={"WdEqTUbWe"}
						>
							<Link
								href={Kekq9f1i5}
								motionChild={true}
								nodeId={"Cr5pNIbfe"}
								openInNewTab={false}
								scopeId={"HdU3c9dDU"}
							>
								<Image
									as={"a"}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 450) - 0 - 504.6) / 2 +
													0 +
													0) +
												0,
										),
										sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
										...toResponsiveImage(Jikq4K9FE),
									}}
									className={"framer-twhkqp framer-karo1v"}
									data-framer-name={"Blog Card Image"}
									layoutDependency={layoutDependency}
									layoutId={"Cr5pNIbfe"}
									{...addPropertyOverrides(
										{
											QE5tuIzyT: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 450) -
																0 -
																504.6) /
																2 +
																0 +
																0) +
															-15,
													),
													sizes: `calc(${componentViewport?.width || "100vw"} * 1.0986)`,
													...toResponsiveImage(Jikq4K9FE),
												},
											},
											RnbzNHxWd: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 508) -
																0 -
																562.6) /
																2 +
																0 +
																0) +
															0,
													),
													sizes: componentViewport?.width || "100vw",
													...toResponsiveImage(Jikq4K9FE),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</Link>
						</motion.div>
						<motion.div
							className={"framer-1dh92qy"}
							data-framer-name={"Blog Card Body"}
							layoutDependency={layoutDependency}
							layoutId={"HhyznHR2p"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1cezqxz"}
								data-framer-name={"Blog Card Date"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"NvGrpbvXy"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56))",
								}}
								text={lyVKu539X}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1sb8f1f"}
										data-styles-preset={"Clb2Z6A0U"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)))",
										}}
									>
										{"August 28, 2023"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-19agbv2"}
								data-framer-name={"Blog Card Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"vBxUIeU7Q"}
								text={QcaJUmNfx}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-1pkgc8z"}
										data-styles-preset={"f9z7v91ro"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										<Link
											href={Kekq9f1i5}
											motionChild={true}
											nodeId={"vBxUIeU7Q"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"HdU3c9dDU"}
											smoothScroll={false}
										>
											<motion.a
												className={"framer-styles-preset-sijqht"}
												data-styles-preset={"LseYDyRFN"}
											>
												{"How to choose the best bedroom decor"}
											</motion.a>
										</Link>
									</motion.h4>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-7pj3m.framer-karo1v, .framer-7pj3m .framer-karo1v { display: block; }",
	".framer-7pj3m.framer-1l433sg { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 416px; }",
	".framer-7pj3m .framer-11z93t5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 303px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-7pj3m .framer-twhkqp { aspect-ratio: 1.372937293729373 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 303px); position: relative; text-decoration: none; width: 1px; }",
	".framer-7pj3m .framer-1dh92qy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-7pj3m .framer-1cezqxz, .framer-7pj3m .framer-19agbv2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-7pj3m.framer-v-1wd7e3n.framer-1l433sg { gap: 34px; }",
	".framer-7pj3m.framer-v-1wd7e3n .framer-11z93t5 { align-content: flex-start; align-items: flex-start; height: min-content; overflow: visible; }",
	".framer-7pj3m.framer-v-1wd7e3n .framer-twhkqp { aspect-ratio: 1.158774373259053 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 359px); width: 100%; }",
	".framer-7pj3m.framer-v-eyhbr0 .framer-twhkqp { flex: none; height: var(--framer-aspect-ratio-supported, 333px); width: 110%; }",
	...css,
	...css2,
	...css3,
];
var FramerHdU3c9dDU = withCSS(Component, css4, "framer-7pj3m");
var stdin_default = FramerHdU3c9dDU;
FramerHdU3c9dDU.displayName = "Blog Card";
FramerHdU3c9dDU.defaultProps = {
	height: 450,
	width: 416,
};
addPropertyControls(FramerHdU3c9dDU, {
	variant: {
		options: ["yXOQhTaw7", "RnbzNHxWd", "QE5tuIzyT"],
		optionTitles: ["Default", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Jikq4K9FE: {
		__defaultAssetReference:
			"data:framer/asset-reference,hLQUNN19E0OvmJl9cRFV0fA4nA.jpg?originalFilename=Image.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	lyVKu539X: {
		defaultValue: "August 28, 2023",
		displayTextArea: false,
		title: "Date",
		type: ControlType.String,
	},
	QcaJUmNfx: {
		defaultValue: "How to choose the best bedroom decor",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	Kekq9f1i5: {
		title: "Link ",
		type: ControlType.Link,
	},
});
addFonts(
	FramerHdU3c9dDU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blog-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "yXOQhTaw7",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var blog_card_default = ComponentWithRoot;
export { blog_card_default as default };
