// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-WM2H2GCJ.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:button-area-3
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jw5RrxtPQ8KAb8UHoEil/WcvcKuimZPantH7rKD6k/LAyCHBaFw.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	CycleVariantState,
	Fetcher,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	usePrefetch,
	usePreloadQuery,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BuyTemplateButtonFonts = getFonts(stdin_default);
var serializationHash = "framer-86jEr";
var variantClassNames = {
	wkCWUd0Vv: "framer-v-i72yzh",
};
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 615,
	type: "spring",
};
var query = (prefetch) =>
	prefetch({
		cacheDuration: 0,
		credentials: "same-origin",
		errorFallbackValue: "Error",
		fallbackValue: "Unlock 200+ Templates",
		resultKeyPath: "framerbite",
		resultOutputType: "string",
		url: `https://grayic.com/api/text-api.php`,
	});
var toString = (value) => {
	return typeof value === "string" ? value : String(value);
};
var query1 = (prefetch) =>
	prefetch({
		cacheDuration: 0,
		credentials: "same-origin",
		errorFallbackValue: "Error",
		fallbackValue: "Access 4500+ Components",
		resultKeyPath: "grayblocks",
		resultOutputType: "string",
		url: `https://grayic.com/api/text-api.php`,
	});
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var preload = async (prequery, prefetch, props) =>
	await Promise.all([query(prefetch), query1(prefetch)]);
var preloadStatements = {
	wkCWUd0Vv: preload,
};
var useLoadingVariant = (
	variant,
	gestures,
	clearLoadingVariant,
	setGestureState,
	props,
) => {
	const prequery = usePreloadQuery();
	const prefetch = usePrefetch();
	React.useEffect(() => {
		const promise = preloadStatements[variant];
		if (!promise || !gestures?.[variant]?.loading) return;
		promise(prequery, prefetch, props)
			.then(() => clearLoadingVariant())
			.catch(() =>
				setGestureState({
					isError: true,
				}),
			);
	}, [variant]);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "wkCWUd0Vv",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppeargnqhaj = activeVariantCallback(async (...args) => {
		setVariant(CycleVariantState);
	});
	useOnVariantChange(baseVariant, {
		default: onAppeargnqhaj,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	useLoadingVariant(baseVariant, void 0, clearLoadingGesture, setGestureState);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-i72yzh",
							className,
							classNames,
						)}
						data-framer-name={"Remove This Buy Promo"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"wkCWUd0Vv"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(8px)",
							backgroundColor: "rgba(255, 255, 255, 0.06)",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							WebkitBackdropFilter: "blur(8px)",
							...style,
						}}
					>
						<ComponentViewportProvider
							height={46}
							width={`calc(${componentViewport?.width || "100vw"} - 20px)`}
							y={
								(componentViewport?.y || 0) +
								10 +
								(((componentViewport?.height || 174) - 20 - 154) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-sbrfh6-container"}
								data-framer-name={"Remove This Buy Button"}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"kgVFoOcuX-container"}
								name={"Remove This Buy Button"}
								nodeId={"kgVFoOcuX"}
								rendersWithMotion={true}
								scopeId={"LAyCHBaFw"}
							>
								{_jsx(stdin_default, {
									aPUmHmVE4: "corner-up-right",
									cduyS1Ada: "https://framerbite.com/product/hotel-six",
									height: "100%",
									id: "kgVFoOcuX",
									layoutId: "kgVFoOcuX",
									ldCLyM4KN: "rgb(255, 255, 255)",
									mdYS8aWFV: "rgb(0, 0, 0)",
									name: "Remove This Buy Button",
									style: {
										width: "100%",
									},
									tjMXlWKyS: "rgb(0, 0, 0)",
									width: "100%",
									yoHhge7xS: "Get This Template",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<Fetcher
							disabled={isLoading}
							requests={[
								{
									cacheDuration: 0,
									credentials: "same-origin",
									errorFallbackValue: "Error",
									fallbackValue: "Unlock 200+ Templates",
									resultKeyPath: "framerbite",
									resultOutputType: "string",
									url: `https://grayic.com/api/text-api.php`,
								},
							]}
						>
							{(fetchResult) => (
								<ComponentViewportProvider
									height={46}
									width={`calc(${componentViewport?.width || "100vw"} - 20px)`}
									y={
										(componentViewport?.y || 0) +
										10 +
										(((componentViewport?.height || 174) - 20 - 154) / 2 +
											46 +
											8)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-17zbwol-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"oh6g_YkSk-container"}
										nodeId={"oh6g_YkSk"}
										rendersWithMotion={true}
										scopeId={"LAyCHBaFw"}
									>
										{_jsx(stdin_default, {
											aPUmHmVE4: "layout",
											cduyS1Ada: "https://framerbite.com/all-access",
											height: "100%",
											id: "oh6g_YkSk",
											layoutId: "oh6g_YkSk",
											ldCLyM4KN:
												"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
											mdYS8aWFV: "rgb(255, 255, 255)",
											style: {
												width: "100%",
											},
											tjMXlWKyS: "rgb(255, 255, 255)",
											width: "100%",
											yoHhge7xS: toString(fetchResult[0]),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</Fetcher>
						<Fetcher
							disabled={isLoading}
							requests={[
								{
									cacheDuration: 0,
									credentials: "same-origin",
									errorFallbackValue: "Error",
									fallbackValue: "Access 4500+ Components",
									resultKeyPath: "grayblocks",
									resultOutputType: "string",
									url: `https://grayic.com/api/text-api.php`,
								},
							]}
						>
							{(fetchResult1) => (
								<ComponentViewportProvider
									height={46}
									width={`calc(${componentViewport?.width || "100vw"} - 20px)`}
									y={
										(componentViewport?.y || 0) +
										10 +
										(((componentViewport?.height || 174) - 20 - 154) / 2 +
											92 +
											16)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-1qj0if6-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"y0zgrKAtM-container"}
										nodeId={"y0zgrKAtM"}
										rendersWithMotion={true}
										scopeId={"LAyCHBaFw"}
									>
										{_jsx(stdin_default, {
											aPUmHmVE4: "layers",
											cduyS1Ada: "https://grayblocks.net/",
											height: "100%",
											id: "y0zgrKAtM",
											layoutId: "y0zgrKAtM",
											ldCLyM4KN: "rgb(20, 20, 20)",
											mdYS8aWFV: "rgb(255, 255, 255)",
											style: {
												width: "100%",
											},
											tjMXlWKyS: "rgb(255, 255, 255)",
											width: "100%",
											yoHhge7xS: toString(fetchResult1[0]),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</Fetcher>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-86jEr.framer-7r4e9v, .framer-86jEr .framer-7r4e9v { display: block; }",
	".framer-86jEr.framer-i72yzh { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 10px; position: relative; width: 280px; }",
	".framer-86jEr .framer-sbrfh6-container, .framer-86jEr .framer-17zbwol-container, .framer-86jEr .framer-1qj0if6-container { flex: none; height: auto; position: relative; width: 100%; z-index: 1; }",
];
var FramerLAyCHBaFw = withCSS(Component, css, "framer-86jEr");
var stdin_default2 = FramerLAyCHBaFw;
FramerLAyCHBaFw.displayName = "Button Area 3";
FramerLAyCHBaFw.defaultProps = {
	height: 174,
	width: 280,
};
addFonts(
	FramerLAyCHBaFw,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...BuyTemplateButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-area-3
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonArea3FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var button_area_3_default = ComponentWithRoot;
export { button_area_3_default as default };
