// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'On Hover' // Variant
 * text?: string // Text
 * link?: string // Link
 * newTab?: boolean // New Tab
}} Props

 */
import {
	NullState,
	defaultEvents,
	useIconSelection,
} from "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:button-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vFrVdJrZ9L1MgM2k2RM8/CTB0vXVxJhoEJVZ3ZZjW/llV2REFlc.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/hKjtTuWGYB451ckw6eTN/bbq95ZQZ142lE2fXscHd/Hero.js
import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { useState, useEffect, useRef } from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { motion } from "unframer";

// /:https://framerusercontent.com/modules/eTFACFXlvp5mgG2YpBpd/wqDmZcxkThZ32xkBavIK/Home.js
var Component;
var Home_default = (React3) => {
	if (!Component) {
		const HomeIcon = React3.forwardRef(function HomeIcon2(
			{ title, titleId, ...props },
			svgRef,
		) {
			return /* @__PURE__ */ React3.createElement(
				"svg",
				Object.assign(
					{
						xmlns: "http://www.w3.org/2000/svg",
						viewBox: "0 0 24 24",
						fill: "currentColor",
						"aria-hidden": "true",
						"data-slot": "icon",
						ref: svgRef,
						"aria-labelledby": titleId,
					},
					props,
				),
				title
					? /* @__PURE__ */ React3.createElement(
							"title",
							{
								id: titleId,
							},
							title,
						)
					: null,
				/* @__PURE__ */ React3.createElement("path", {
					d: "M11.47 3.841a.75.75 0 0 1 1.06 0l8.69 8.69a.75.75 0 1 0 1.06-1.061l-8.689-8.69a2.25 2.25 0 0 0-3.182 0l-8.69 8.69a.75.75 0 1 0 1.061 1.06l8.69-8.689Z",
				}),
				/* @__PURE__ */ React3.createElement("path", {
					d: "m12 5.432 8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 0-.75-.75h-3a.75.75 0 0 0-.75.75V21a.75.75 0 0 1-.75.75H5.625a1.875 1.875 0 0 1-1.875-1.875v-6.198a2.29 2.29 0 0 0 .091-.086L12 5.432Z",
				}),
			);
		});
		Component = HomeIcon;
	}
	return Component;
};

// /:https://framerusercontent.com/modules/hKjtTuWGYB451ckw6eTN/bbq95ZQZ142lE2fXscHd/Hero.js
var iconKeys = [
	"AcademicCap",
	"AdjustmentsVertical",
	"ArchiveBox",
	"ArchiveBoxArrowDown",
	"ArchiveBoxXMark",
	"ArrowDown",
	"ArrowDownCircle",
	"ArrowDownLeft",
	"ArrowDownOnSquare",
	"ArrowDownRight",
	"ArrowDownTray",
	"ArrowLeft",
	"ArrowLeftCircle",
	"ArrowLeftOnRectangle",
	"ArrowLongDown",
	"ArrowLongLeft",
	"ArrowLongRight",
	"ArrowLongUp",
	"ArrowPath",
	"ArrowRight",
	"ArrowRightCircle",
	"ArrowSmallDown",
	"ArrowSmallLeft",
	"ArrowSmallRight",
	"ArrowSmallUp",
	"ArrowTrendingDown",
	"ArrowTrendingUp",
	"ArrowUp",
	"ArrowUpCircle",
	"ArrowUpLeft",
	"ArrowUpOnSquare",
	"ArrowUpOnSquareStack",
	"ArrowUpRight",
	"ArrowUpTray",
	"ArrowUturnDown",
	"ArrowUturnLeft",
	"ArrowUturnRight",
	"ArrowUturnUp",
	"ArrowsPointingIn",
	"ArrowsPointingOut",
	"ArrowsRightLeft",
	"ArrowsUpDown",
	"AtSymbol",
	"Backspace",
	"Backward",
	"Banknotes",
	"Bars2",
	"Bars3",
	"Bars3BottomLeft",
	"Bars3BottomRight",
	"Bars3CenterLeft",
	"Bars4",
	"BarsArrowDown",
	"BarsArrowUp",
	"Battery0",
	"Battery100",
	"Battery50",
	"Beaker",
	"Bell",
	"BellAlert",
	"BellSlash",
	"BellSnooze",
	"Bolt",
	"BoltSlash",
	"BookOpen",
	"Bookmark",
	"BookmarkSlash",
	"BookmarkSquare",
	"Briefcase",
	"BugAnt",
	"BuildingLibrary",
	"BuildingOffice",
	"BuildingOffice2",
	"BuildingStorefront",
	"Cake",
	"Calculator",
	"Calendar",
	"CalendarDays",
	"Camera",
	"ChartBar",
	"ChartBarSquare",
	"ChartPie",
	"ChatBubbleLeft",
	"ChatBubbleLeftRight",
	"ChatBubbleOvalLeft",
	"Check",
	"CheckBadge",
	"CheckCircle",
	"ChevronDoubleDown",
	"ChevronDoubleLeft",
	"ChevronDoubleRight",
	"ChevronDoubleUp",
	"ChevronDown",
	"ChevronLeft",
	"ChevronRight",
	"ChevronUp",
	"ChevronUpDown",
	"CircleStack",
	"Clipboard",
	"ClipboardDocument",
	"Clock",
	"Cloud",
	"CloudArrowDown",
	"CloudArrowUp",
	"CodeBracket",
	"CodeBracketSquare",
	"Cog",
	"Cog6Tooth",
	"Cog8Tooth",
	"CommandLine",
	"ComputerDesktop",
	"CpuChip",
	"CreditCard",
	"Cube",
	"CubeTransparent",
	"CurrencyBangladeshi",
	"CurrencyDollar",
	"CurrencyEuro",
	"CurrencyPound",
	"CurrencyRupee",
	"CurrencyYen",
	"CursorArrowRays",
	"CursorArrowRipple",
	"DevicePhoneMobile",
	"DeviceTablet",
	"Document",
	"DocumentArrowDown",
	"DocumentArrowUp",
	"DocumentChartBar",
	"DocumentCheck",
	"DocumentDuplicate",
	"DocumentMinus",
	"DocumentPlus",
	"DocumentText",
	"EllipsisHorizontal",
	"EllipsisVertical",
	"Envelope",
	"EnvelopeOpen",
	"ExclamationCircle",
	"ExclamationTriangle",
	"Eye",
	"EyeDropper",
	"EyeSlash",
	"FaceFrown",
	"FaceSmile",
	"Film",
	"FingerPrint",
	"Fire",
	"Flag",
	"Folder",
	"FolderArrowDown",
	"FolderMinus",
	"FolderOpen",
	"FolderPlus",
	"Forward",
	"Funnel",
	"Gif",
	"Gift",
	"GiftTop",
	"GlobeAlt",
	"GlobeAmericas",
	"GlobeAsiaAustralia",
	"GlobeEuropeAfrica",
	"HandRaised",
	"HandThumbDown",
	"HandThumbUp",
	"Hashtag",
	"Heart",
	"Home",
	"HomeModern",
	"Identification",
	"Inbox",
	"InboxArrowDown",
	"InboxStack",
	"InformationCircle",
	"Key",
	"Language",
	"Lifebuoy",
	"LightBulb",
	"Link",
	"ListBullet",
	"LockClosed",
	"LockOpen",
	"MagnifyingGlass",
	"MagnifyingGlassMinus",
	"MagnifyingGlassPlus",
	"Map",
	"MapPin",
	"Megaphone",
	"Microphone",
	"Minus",
	"MinusCircle",
	"MinusSmall",
	"Moon",
	"MusicalNote",
	"Newspaper",
	"NoSymbol",
	"PaintBrush",
	"PaperAirplane",
	"PaperClip",
	"Pause",
	"PauseCircle",
	"Pencil",
	"PencilSquare",
	"Phone",
	"PhoneArrowDownLeft",
	"PhoneArrowUpRight",
	"PhoneXMark",
	"Photo",
	"Play",
	"PlayCircle",
	"PlayPause",
	"Plus",
	"PlusCircle",
	"PlusSmall",
	"Power",
	"PresentationChartBar",
	"Printer",
	"PuzzlePiece",
	"QrCode",
	"QuestionMarkCircle",
	"QueueList",
	"Radio",
	"ReceiptPercent",
	"ReceiptRefund",
	"RectangleGroup",
	"RectangleStack",
	"RocketLaunch",
	"Rss",
	"Scale",
	"Scissors",
	"Server",
	"ServerStack",
	"Share",
	"ShieldCheck",
	"ShieldExclamation",
	"ShoppingBag",
	"ShoppingCart",
	"Signal",
	"SignalSlash",
	"Sparkles",
	"SpeakerWave",
	"SpeakerXMark",
	"Square2Stack",
	"Square3Stack3D",
	"Squares2X2",
	"SquaresPlus",
	"Star",
	"Stop",
	"StopCircle",
	"Sun",
	"Swatch",
	"TableCells",
	"Tag",
	"Ticket",
	"Trash",
	"Trophy",
	"Truck",
	"Tv",
	"User",
	"UserCircle",
	"UserGroup",
	"UserMinus",
	"UserPlus",
	"Users",
	"Variable",
	"VideoCamera",
	"VideoCameraSlash",
	"ViewColumns",
	"ViewfinderCircle",
	"Wallet",
	"Wifi",
	"Window",
	"Wrench",
	"WrenchScrewdriver",
	"XCircle",
	"XMark",
	"index",
];
var moduleBaseUrl = "https://framer.com/m/hero-icons/";
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
	res[key.toLowerCase()] = key;
	return res;
}, {});
function Icon(props) {
	const {
		color,
		selectByList,
		iconSearch,
		iconSelection,
		onClick,
		onMouseDown,
		onMouseUp,
		onMouseEnter,
		onMouseLeave,
		mirrored,
	} = props;
	const isMounted = useRef(false);
	const iconKey = useIconSelection(
		iconKeys,
		selectByList,
		iconSearch,
		iconSelection,
		lowercaseIconKeyPairs,
	);
	const [SelectedIcon, setSelectedIcon] = useState(
		iconKey === "Home" ? Home_default(React) : null,
	);
	async function importModule() {
		try {
			const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@0.0.28`;
			const module = await import(
				/* webpackIgnore: true */
				/* @vite-ignore */
				iconModuleUrl
			);
			if (isMounted.current) setSelectedIcon(module.default(React));
		} catch {
			if (isMounted.current) setSelectedIcon(null);
		}
	}
	useEffect(() => {
		isMounted.current = true;
		importModule();
		return () => {
			isMounted.current = false;
		};
	}, [iconKey]);
	const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
	const emptyState = isOnCanvas ? <NullState /> : null;
	return (
		<motion.div
			style={{
				display: "contents",
			}}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
		>
			{SelectedIcon ? (
				<SelectedIcon
					style={{
						width: "100%",
						height: "100%",
						transform: mirrored ? "scale(-1, 1)" : void 0,
					}}
					color={color}
				/>
			) : (
				emptyState
			)}
		</motion.div>
	);
}
Icon.displayName = "Hero";
Icon.defaultProps = {
	width: 24,
	height: 24,
	iconSelection: "Home",
	iconSearch: "Home",
	color: "#66F",
	selectByList: true,
	mirrored: false,
};
addPropertyControls(Icon, {
	selectByList: {
		type: ControlType.Boolean,
		title: "Select",
		enabledTitle: "List",
		disabledTitle: "Search",
		defaultValue: Icon.defaultProps.selectByList,
	},
	iconSelection: {
		type: ControlType.Enum,
		options: iconKeys,
		defaultValue: Icon.defaultProps.iconSelection,
		title: "Name",
		hidden: ({ selectByList }) => !selectByList,
		description:
			"Find every icon name on the [Hero site](https://heroicons.com/)",
	},
	iconSearch: {
		type: ControlType.String,
		title: "Name",
		placeholder: "Menu, Wifi, Box\u2026",
		hidden: ({ selectByList }) => selectByList,
	},
	mirrored: {
		type: ControlType.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: Icon.defaultProps.mirrored,
	},
	color: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: Icon.defaultProps.color,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/zDoKmqdlopFDykVeea1c/me2DaGVuBgrWqLiq2muk/dRtQy1Bem.js
import { fontStore } from "unframer";
fontStore.loadWebFontsFromSelectors(["GF;Barlow-600"]);
var fonts = [
	{
		family: "Barlow",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/dRtQy1Bem:default",
			url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E30-8c4FAtlT47dw.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E30-8c4FAtlT47dw.ttf",
		weight: "600",
	},
];
var css = [
	'.framer-Zb0zv .framer-styles-preset-19zygmk:not(.rich-text-wrapper), .framer-Zb0zv .framer-styles-preset-19zygmk.rich-text-wrapper p { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-weight: 600; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: right; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; }',
];
var className = "framer-Zb0zv";

// /:https://framerusercontent.com/modules/vFrVdJrZ9L1MgM2k2RM8/CTB0vXVxJhoEJVZ3ZZjW/llV2REFlc.js
var HeroFonts = getFonts(Icon);
var cycleOrder = ["P3SsFZrog", "fnIxQVceG"];
var serializationHash = "framer-JboQj";
var variantClassNames = {
	fnIxQVceG: "framer-v-dtv0vf",
	P3SsFZrog: "framer-v-plmnqe",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"On Hover": "fnIxQVceG",
	Default: "P3SsFZrog",
};
var getProps = ({ height, id, link, newTab, text, width, ...props }) => {
	return {
		...props,
		awpzToRaD: link ?? props.awpzToRaD,
		f4pCYIS9S: newTab ?? props.f4pCYIS9S,
		J_npqCzpg: text ?? props.J_npqCzpg ?? "View All Rooms",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "P3SsFZrog",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		J_npqCzpg,
		awpzToRaD,
		f4pCYIS9S,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "P3SsFZrog",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEntertgfqka = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("fnIxQVceG");
	});
	const onMouseLeave1azbaam = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("P3SsFZrog");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={awpzToRaD}
						motionChild={true}
						nodeId={"P3SsFZrog"}
						openInNewTab={f4pCYIS9S}
						scopeId={"llV2REFlc"}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-plmnqe", className2, classNames)} framer-13piyzo`}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"P3SsFZrog"}
							onMouseEnter={onMouseEntertgfqka}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									fnIxQVceG: {
										"data-framer-name": "On Hover",
										onMouseEnter: void 0,
										onMouseLeave: onMouseLeave1azbaam,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ve8glc"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"I7919:31;7308:1703"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
								}}
								text={J_npqCzpg}
								verticalAlignment={"center"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-19zygmk"}
										data-styles-preset={"dRtQy1Bem"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83)))",
										}}
									>
										{"View All Rooms"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-dscize-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"tk5_XcCvo-container"}
									nodeId={"tk5_XcCvo"}
									rendersWithMotion={true}
									scopeId={"llV2REFlc"}
								>
									<Icon
										color={
											"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))"
										}
										height={"100%"}
										iconSearch={"Home"}
										iconSelection={"ArrowRight"}
										id={"tk5_XcCvo"}
										layoutId={"tk5_XcCvo"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JboQj.framer-13piyzo, .framer-JboQj .framer-13piyzo { display: block; }",
	".framer-JboQj.framer-plmnqe { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 2px 0px 2px 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-JboQj .framer-ve8glc { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-JboQj .framer-dscize-container { aspect-ratio: 1 / 1; bottom: 2px; flex: none; height: var(--framer-aspect-ratio-supported, 19px); position: absolute; right: -21px; width: 16px; z-index: 1; }",
	".framer-JboQj.framer-v-dtv0vf .framer-dscize-container { right: -25px; }",
	...css,
];
var FramerllV2REFlc = withCSS(Component2, css2, "framer-JboQj");
var stdin_default = FramerllV2REFlc;
FramerllV2REFlc.displayName = "Button Link";
FramerllV2REFlc.defaultProps = {
	height: 28,
	width: 107,
};
addPropertyControls2(FramerllV2REFlc, {
	variant: {
		options: ["P3SsFZrog", "fnIxQVceG"],
		optionTitles: ["Default", "On Hover"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	J_npqCzpg: {
		defaultValue: "View All Rooms",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
	awpzToRaD: {
		title: "Link",
		type: ControlType2.Link,
	},
	f4pCYIS9S: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType2.Boolean,
	},
});
addFonts(
	FramerllV2REFlc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...HeroFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "P3SsFZrog",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_link_default = ComponentWithRoot;
export { button_link_default as default };
