// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Small' // Variant
 * text?: string // Text
 * contactInfo?: string // Contact Info
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-BCA7MXE7.js";
import { className, css, fonts } from "./chunks/chunk-J7DO4Q5N.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-RQLRFZ7Z.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:contact-widget
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vRIwaxW60eghr4sr9cmZ/yq0hGpGXoG0J4lTCzXqS/AQH7XZ4GH.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/usO1L63SbctLeqrcXTSN/4rvVft9G7uLcVCl6iPnW/iAhJnX60t.js
import { fontStore } from "unframer";
fontStore.loadWebFontsFromSelectors(["GF;Barlow-600"]);
var fonts4 = [
	{
		family: "Barlow",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/iAhJnX60t:default",
			url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E30-8c4FAtlT47dw.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E30-8c4FAtlT47dw.ttf",
		weight: "600",
	},
];
var css4 = [
	'.framer-z5fAQ .framer-styles-preset-nxsqy6:not(.rich-text-wrapper), .framer-z5fAQ .framer-styles-preset-nxsqy6.rich-text-wrapper h4 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-weight: 600; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 768px) { .framer-z5fAQ .framer-styles-preset-nxsqy6:not(.rich-text-wrapper), .framer-z5fAQ .framer-styles-preset-nxsqy6.rich-text-wrapper h4 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-weight: 600; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 767px) and (min-width: 0px) { .framer-z5fAQ .framer-styles-preset-nxsqy6:not(.rich-text-wrapper), .framer-z5fAQ .framer-styles-preset-nxsqy6.rich-text-wrapper h4 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-weight: 600; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className4 = "framer-z5fAQ";

// /:https://framerusercontent.com/modules/cyqSPQO4hTxcYJWTaNtu/4a138BnjsQkf7s8tfRg1/wVXLImF39.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadWebFontsFromSelectors(["GF;Barlow-500"]);
var fonts5 = [
	{
		family: "Barlow",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/wVXLImF39:default",
			url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E3_-gc4FAtlT47dw.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E3_-gc4FAtlT47dw.ttf",
		weight: "500",
	},
];
var css5 = [
	'.framer-5HHu4 .framer-styles-preset-lx2mei:not(.rich-text-wrapper), .framer-5HHu4 .framer-styles-preset-lx2mei.rich-text-wrapper h4 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.0208333em; --framer-line-height: 140%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-5HHu4 .framer-styles-preset-lx2mei:not(.rich-text-wrapper), .framer-5HHu4 .framer-styles-preset-lx2mei.rich-text-wrapper h4 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.0208333em; --framer-line-height: 140%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-5HHu4 .framer-styles-preset-lx2mei:not(.rich-text-wrapper), .framer-5HHu4 .framer-styles-preset-lx2mei.rich-text-wrapper h4 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.0208333em; --framer-line-height: 140%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className5 = "framer-5HHu4";

// /:https://framerusercontent.com/modules/vRIwaxW60eghr4sr9cmZ/yq0hGpGXoG0J4lTCzXqS/AQH7XZ4GH.js
var cycleOrder = ["oK_JFGgbZ", "enLtyupZt"];
var serializationHash = "framer-PJSvP";
var variantClassNames = {
	enLtyupZt: "framer-v-1gzkfjs",
	oK_JFGgbZ: "framer-v-18xrb70",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "oK_JFGgbZ",
	Small: "enLtyupZt",
};
var getProps = ({ contactInfo, height, id, text, width, ...props }) => {
	return {
		...props,
		IR6cC5vt3: contactInfo ?? props.IR6cC5vt3 ?? "+47 988 07 242",
		JgHsAGQBj: text ?? props.JgHsAGQBj ?? "Reservasjon",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "oK_JFGgbZ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		JgHsAGQBj: JgHsAGQBj2,
		IR6cC5vt3: IR6cC5vt32,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "oK_JFGgbZ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className,
		className4,
		className3,
		className5,
		className2,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-18xrb70",
							className6,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"oK_JFGgbZ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								enLtyupZt: {
									"data-framer-name": "Small",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<SVG
							className={"framer-15o3iux"}
							data-framer-name={"phone-call "}
							fill={"rgba(0,0,0,1)"}
							intrinsicHeight={58}
							intrinsicWidth={58}
							layoutDependency={layoutDependency}
							layoutId={"CjKRlRKCq"}
							svg={
								'<svg width="58" height="58" viewBox="0 0 58 58" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M33.8335 2.41699C39.602 2.41699 45.1342 4.7085 49.2131 8.78742C53.292 12.8663 55.5835 18.3985 55.5835 24.167" stroke="#E4A853" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M33.8335 12.084C37.0382 12.084 40.1116 13.357 42.3777 15.6231C44.6438 17.8892 45.9168 20.9626 45.9168 24.1673" stroke="#E4A853" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M37.5079 34.9699L33.3718 40.1404C26.9657 36.3755 21.627 31.0372 17.8616 24.6314L23.0321 20.4953C23.6379 20.0101 24.0661 19.338 24.2497 18.5838C24.4333 17.8297 24.3621 17.0359 24.0471 16.3265L19.3334 5.71374C18.9955 4.95235 18.3982 4.33574 17.648 3.97388C16.8977 3.61203 16.0433 3.52847 15.2371 3.73812L6.26645 6.06537C5.42925 6.2841 4.70138 6.80236 4.22078 7.52192C3.74017 8.24149 3.54024 9.11236 3.65887 9.96949C5.23338 21.1812 10.4151 31.5755 18.4208 39.5812C26.4265 47.5869 36.8208 52.7686 48.0325 54.3431C48.8894 54.4614 49.76 54.2613 50.4793 53.7808C51.1986 53.3002 51.7167 52.5725 51.9354 51.7355L54.2627 42.7637C54.4719 41.9577 54.3883 41.1036 54.0267 40.3534C53.6651 39.6033 53.0491 39.0058 52.2882 38.6674L41.6767 33.9549C40.9673 33.6397 40.1735 33.5683 39.4193 33.752C38.6651 33.9356 37.993 34.3639 37.5079 34.9699Z" stroke="#E4A853" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
							}
							withExternalLayout={true}
						/>
						<motion.div
							className={"framer-zwvsmn"}
							data-framer-name={"Contact Widget Body"}
							layoutDependency={layoutDependency}
							layoutId={"xbCIdLvB9"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1qwixg9"}
								data-framer-name={"Contact Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"xGwvWWu2w"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-636a3fe4-9f0f-4ae1-a43c-60a743a1245b, rgb(245, 242, 238))",
								}}
								text={JgHsAGQBj2}
								variants={{
									enLtyupZt: {
										"--extracted-r6o4lv":
											"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										enLtyupZt: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1sb8f1f"}
														data-styles-preset={"Clb2Z6A0U"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)))",
														}}
													>
														{"Reservation"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1sb8f1f"}
										data-styles-preset={"Clb2Z6A0U"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-636a3fe4-9f0f-4ae1-a43c-60a743a1245b, rgb(245, 242, 238)))",
										}}
									>
										{"Reservation"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-5jlyub"}
								data-framer-name={"Contact Number"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"jzxN51ZsS"}
								style={{
									"--extracted-1eung3n":
										"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
								}}
								variants={{
									enLtyupZt: {
										"--extracted-1eung3n":
											"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										enLtyupZt: {
											children: (
												<React.Fragment>
													<motion.h4
														className={"framer-styles-preset-lx2mei"}
														data-styles-preset={"wVXLImF39"}
														style={{
															"--framer-text-color":
																"var(--extracted-1eung3n, var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83)))",
														}}
													>
														<Link
															href={"tel:+4798807242"}
															motionChild={true}
															nodeId={"jzxN51ZsS"}
															openInNewTab={true}
															relValues={[]}
															scopeId={"AQH7XZ4GH"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-3d4pe6"}
																data-styles-preset={"J86UbKDyH"}
															>
																{"+47 988 07 242"}
															</motion.a>
														</Link>
													</motion.h4>
												</React.Fragment>
											),
											text: IR6cC5vt32,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-nxsqy6"}
										data-styles-preset={"iAhJnX60t"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)))",
										}}
									>
										<Link
											href={"tel:+4798807242"}
											motionChild={true}
											nodeId={"jzxN51ZsS"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"AQH7XZ4GH"}
											smoothScroll={false}
										>
											<motion.a
												className={"framer-styles-preset-y5s2qt"}
												data-styles-preset={"ybRKRcLeC"}
											>
												{"+47 988 07 242"}
											</motion.a>
										</Link>
									</motion.h4>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PJSvP.framer-slu3lw, .framer-PJSvP .framer-slu3lw { display: block; }",
	".framer-PJSvP.framer-18xrb70 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 17px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 538px; }",
	".framer-PJSvP .framer-15o3iux { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 58px); position: relative; width: 58px; }",
	".framer-PJSvP .framer-zwvsmn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-PJSvP .framer-1qwixg9 { align-self: stretch; flex: none; height: auto; position: relative; white-space: pre-wrap; width: auto; word-break: break-word; word-wrap: break-word; }",
	".framer-PJSvP .framer-5jlyub { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-PJSvP.framer-v-1gzkfjs.framer-18xrb70 { gap: 20px; }",
	".framer-PJSvP.framer-v-1gzkfjs .framer-15o3iux { height: var(--framer-aspect-ratio-supported, 50px); width: 50px; }",
	...css,
	...css4,
	...css3,
	...css5,
	...css2,
];
var FramerAQH7XZ4GH = withCSS(Component, css6, "framer-PJSvP");
var stdin_default = FramerAQH7XZ4GH;
FramerAQH7XZ4GH.displayName = "Contact Widget";
FramerAQH7XZ4GH.defaultProps = {
	height: 72,
	width: 538,
};
addPropertyControls(FramerAQH7XZ4GH, {
	variant: {
		options: ["oK_JFGgbZ", "enLtyupZt"],
		optionTitles: ["Default", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	JgHsAGQBj: {
		defaultValue: "Reservasjon",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	IR6cC5vt3: {
		defaultValue: "+47 988 07 242",
		displayTextArea: false,
		placeholder: "",
		title: "Contact Info",
		type: ControlType.String,
	},
});
addFonts(
	FramerAQH7XZ4GH,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:contact-widget
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "oK_JFGgbZ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactWidgetFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var contact_widget_default = ComponentWithRoot;
export { contact_widget_default as default };
