// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Gray' | 'White' | 'Mobile' // Variant
}} Props

 */
import {
	className,
	className2,
	css,
	css2,
	fonts,
	fonts2,
} from "./chunks/chunk-A2LYUWB4.js";
import { stdin_default } from "./chunks/chunk-LSZ6YBU4.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:cta-form-block
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fLVY8mUPiiuUXQJhQx57/24I4tdHEiQwBO1yQ46Ji/XNVvgS1rM.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	FormPlainTextInput,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var Button2Fonts = getFonts(stdin_default);
var cycleOrder = ["L2fQSkE_G", "SGW63zoAz", "bxatap7yZ"];
var serializationHash = "framer-RDV60";
var variantClassNames = {
	bxatap7yZ: "framer-v-ngoxba",
	L2fQSkE_G: "framer-v-t99dwh",
	SGW63zoAz: "framer-v-op7bj9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
		default:
			return currentVariant;
	}
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Gray: "L2fQSkE_G",
	Mobile: "bxatap7yZ",
	White: "SGW63zoAz",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "L2fQSkE_G",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "L2fQSkE_G",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-t99dwh",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Gray"}
						layoutDependency={layoutDependency}
						layoutId={"L2fQSkE_G"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56))",
							...style,
						}}
						variants={{
							SGW63zoAz: {
								backgroundColor:
									"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56))",
							},
						}}
						{...addPropertyOverrides(
							{
								bxatap7yZ: {
									"data-framer-name": "Mobile",
								},
								SGW63zoAz: {
									"data-framer-name": "White",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1iin68"}
							data-framer-name={"Form Text Block"}
							layoutDependency={layoutDependency}
							layoutId={"A69IkqlZY"}
						>
							<motion.div
								className={"framer-18yf5g7"}
								data-framer-name={"Title Block"}
								layoutDependency={layoutDependency}
								layoutId={"W3TmQfqoB"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-itfeoi"}
									data-framer-name={"Subtitle"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"EkUfxvako"}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-x2j49s"}
											data-styles-preset={"jYkXtflJ5"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color": "rgb(255, 255, 255)",
											}}
										>
											{"Fjellheimen"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-i9g8sd"}
									data-framer-name={"Form Title"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"KBCbexn4F"}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1pkgc8z"}
											data-styles-preset={"f9z7v91ro"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color": "rgb(255, 255, 255)",
											}}
										>
											{"Booke hotellet?"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
							<SVG
								className={"framer-13neqbi"}
								data-framer-name={"Divider"}
								fill={"rgba(0,0,0,1)"}
								intrinsicHeight={4}
								intrinsicWidth={442}
								layoutDependency={layoutDependency}
								layoutId={"xCO2RvPd6"}
								svg={
									'<svg width="442" height="4" viewBox="-1 -1 442 4" fill="none" xmlns="http://www.w3.org/2000/svg">\n<line x1="0.00112867" y1="0.500001" x2="440" y2="1.49323" stroke="#FFFFFF"/>\n</svg>\n'
								}
								withExternalLayout={true}
							/>
						</motion.div>
						<FormContainer
							action={
								"https://api.framer.com/forms/v1/forms/e87d0f0f-7ebd-449f-b7ee-f99401550508/submit"
							}
							className={"framer-1a5caol"}
							layoutDependency={layoutDependency}
							layoutId={"v1cGKtvbo"}
							nodeId={"v1cGKtvbo"}
							submitTrackingId={""}
						>
							{(formState) => (
								<_Fragment>
									<motion.label
										className={"framer-16naxru"}
										layoutDependency={layoutDependency}
										layoutId={"slFACdMYs"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-nemw9"}
											fonts={["Inter-Medium"]}
											layoutDependency={layoutDependency}
											layoutId={"Doh1f0GR1"}
											style={{
												"--extracted-r6o4lv": "rgb(255, 255, 255)",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "SW50ZXItTWVkaXVt",
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"Navn"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<FormPlainTextInput
											className={"framer-1n8b395"}
											inputName={"Name"}
											layoutDependency={layoutDependency}
											layoutId={"O9x_Zc1yM"}
											placeholder={"Kari Nordmann"}
											style={{
												"--framer-input-background":
													"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
												"--framer-input-border-left-width": "1px",
												"--framer-input-border-radius-bottom-left": "10px",
												"--framer-input-border-radius-bottom-right": "10px",
												"--framer-input-border-radius-top-left": "10px",
												"--framer-input-border-radius-top-right": "10px",
												"--framer-input-border-right-width": "1px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "1px",
												"--framer-input-font-color": "rgb(61, 58, 56)",
												"--framer-input-icon-color": "rgb(61, 58, 56)",
												"--framer-input-placeholder-color":
													"rgb(61, 58, 56)",
											}}
											type={"text"}
										/>
									</motion.label>
									<motion.label
										className={"framer-hxvcyx"}
										layoutDependency={layoutDependency}
										layoutId={"cFG1jw5kb"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-mygqva"}
											fonts={["Inter-Medium"]}
											layoutDependency={layoutDependency}
											layoutId={"ZCsNBMhpw"}
											style={{
												"--extracted-r6o4lv": "rgb(255, 255, 255)",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "SW50ZXItTWVkaXVt",
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"E-postadresse"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<FormPlainTextInput
											className={"framer-1trlm4e"}
											inputName={"Email"}
											layoutDependency={layoutDependency}
											layoutId={"MAGznJR5_"}
											placeholder={"kari@nordmann.no"}
											style={{
												"--framer-input-background":
													"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
												"--framer-input-border-left-width": "1px",
												"--framer-input-border-radius-bottom-left": "10px",
												"--framer-input-border-radius-bottom-right": "10px",
												"--framer-input-border-radius-top-left": "10px",
												"--framer-input-border-radius-top-right": "10px",
												"--framer-input-border-right-width": "1px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "1px",
												"--framer-input-font-color": "rgb(61, 58, 56)",
												"--framer-input-icon-color": "rgb(61, 58, 56)",
												"--framer-input-placeholder-color":
													"rgb(61, 58, 56)",
											}}
											type={"email"}
										/>
									</motion.label>
									<motion.label
										className={"framer-99ufrm"}
										layoutDependency={layoutDependency}
										layoutId={"UTdZE7zLE"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-9tn6ak"}
											fonts={["Inter-Medium"]}
											layoutDependency={layoutDependency}
											layoutId={"CrlSeGtVC"}
											style={{
												"--extracted-r6o4lv": "rgb(255, 255, 255)",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "SW50ZXItTWVkaXVt",
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"Mobilnummer"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<FormPlainTextInput
											className={"framer-1h3bz45"}
											inputName={"Email"}
											layoutDependency={layoutDependency}
											layoutId={"RmQyZI45n"}
											placeholder={"11223344"}
											style={{
												"--framer-input-background":
													"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
												"--framer-input-border-left-width": "1px",
												"--framer-input-border-radius-bottom-left": "10px",
												"--framer-input-border-radius-bottom-right": "10px",
												"--framer-input-border-radius-top-left": "10px",
												"--framer-input-border-radius-top-right": "10px",
												"--framer-input-border-right-width": "1px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "1px",
												"--framer-input-font-color": "rgb(61, 58, 56)",
												"--framer-input-icon-color": "rgb(61, 58, 56)",
												"--framer-input-placeholder-color":
													"rgb(61, 58, 56)",
											}}
											type={"tel"}
										/>
									</motion.label>
									<motion.label
										className={"framer-15d3uk6"}
										layoutDependency={layoutDependency}
										layoutId={"tLYTtnNRy"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-tbd0ik"}
											fonts={["Inter-Medium"]}
											layoutDependency={layoutDependency}
											layoutId={"m4F7PFOTL"}
											style={{
												"--extracted-r6o4lv": "rgb(255, 255, 255)",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "SW50ZXItTWVkaXVt",
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"Kommentar"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<FormPlainTextInput
											className={"framer-qjyst"}
											inputName={"Kommentar"}
											layoutDependency={layoutDependency}
											layoutId={"lFldIQ9jb"}
											placeholder={
												"Skriv gjerne et par kommentarer om oppholdet."
											}
											style={{
												"--framer-input-background":
													"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
												"--framer-input-border-left-width": "1px",
												"--framer-input-border-radius-bottom-left": "10px",
												"--framer-input-border-radius-bottom-right": "10px",
												"--framer-input-border-radius-top-left": "10px",
												"--framer-input-border-radius-top-right": "10px",
												"--framer-input-border-right-width": "1px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "1px",
												"--framer-input-font-color": "rgb(61, 58, 56)",
												"--framer-input-icon-color": "rgb(61, 58, 56)",
												"--framer-input-placeholder-color":
													"rgb(61, 58, 56)",
											}}
											type={"textarea"}
										/>
									</motion.label>
									<motion.label
										className={"framer-198dhpf"}
										layoutDependency={layoutDependency}
										layoutId={"AVE41gifh"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1u6jzti"}
											fonts={["Inter-Medium"]}
											layoutDependency={layoutDependency}
											layoutId={"dVPk2aGZr"}
											style={{
												"--extracted-r6o4lv": "rgb(255, 255, 255)",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "SW50ZXItTWVkaXVt",
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(255, 255, 255))",
													}}
												>
													{"N\xE5r vil du booke?"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<FormPlainTextInput
											className={"framer-mmtdv3"}
											inputName={"Dato"}
											layoutDependency={layoutDependency}
											layoutId={"m4CsZCRBM"}
											placeholder={"jane@framer.com"}
											style={{
												"--framer-input-background":
													"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
												"--framer-input-border-bottom-width": "1px",
												"--framer-input-border-color":
													"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
												"--framer-input-border-left-width": "1px",
												"--framer-input-border-radius-bottom-left": "10px",
												"--framer-input-border-radius-bottom-right": "10px",
												"--framer-input-border-radius-top-left": "10px",
												"--framer-input-border-radius-top-right": "10px",
												"--framer-input-border-right-width": "1px",
												"--framer-input-border-style": "solid",
												"--framer-input-border-top-width": "1px",
												"--framer-input-font-color": "rgb(61, 58, 56)",
												"--framer-input-icon-color": "rgb(61, 58, 56)",
												"--framer-input-placeholder-color":
													"rgb(61, 58, 56)",
											}}
											type={"date"}
										/>
									</motion.label>
									<ComponentViewportProvider
										height={50}
										width={"400px"}
										{...addPropertyOverrides(
											{
												bxatap7yZ: {
													width: "245px",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-18kmkf1-container"}
											layoutDependency={layoutDependency}
											layoutId={"swwZ3hhco-container"}
											nodeId={"swwZ3hhco"}
											rendersWithMotion={true}
											scopeId={"XNVvgS1rM"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "swwZ3hhco",
												layoutId: "swwZ3hhco",
												style: {
													height: "100%",
													width: "100%",
												},
												type: "submit",
												variant: formVariants(
													formState,
													{
														pending: "JoTqCzP64",
														success: "lU2Lde8bK",
													},
													"BCn4N_2pN",
												),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</_Fragment>
							)}
						</FormContainer>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RDV60.framer-18qqvq4, .framer-RDV60 .framer-18qqvq4 { display: block; }",
	".framer-RDV60.framer-t99dwh { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 23px; height: min-content; justify-content: center; max-width: 520px; overflow: visible; padding: 40px; position: relative; width: 520px; }",
	".framer-RDV60 .framer-1iin68 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RDV60 .framer-18yf5g7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-RDV60 .framer-itfeoi, .framer-RDV60 .framer-i9g8sd { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-RDV60 .framer-13neqbi { flex: none; height: 4px; position: relative; width: 100%; }",
	".framer-RDV60 .framer-1a5caol { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 20px; position: relative; width: 440px; }",
	".framer-RDV60 .framer-16naxru, .framer-RDV60 .framer-hxvcyx, .framer-RDV60 .framer-99ufrm, .framer-RDV60 .framer-15d3uk6, .framer-RDV60 .framer-198dhpf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-RDV60 .framer-nemw9, .framer-RDV60 .framer-mygqva, .framer-RDV60 .framer-9tn6ak, .framer-RDV60 .framer-tbd0ik, .framer-RDV60 .framer-1u6jzti { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-RDV60 .framer-1n8b395, .framer-RDV60 .framer-1trlm4e, .framer-RDV60 .framer-1h3bz45, .framer-RDV60 .framer-mmtdv3 { --framer-input-focused-border-color: #0099ff; --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Inter"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 14px; --framer-input-font-weight: 400; --framer-input-padding: 12px; flex: none; height: 50px; position: relative; width: 100%; }',
	'.framer-RDV60 .framer-qjyst { --framer-input-focused-border-color: #0099ff; --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Inter"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 14px; --framer-input-font-weight: 400; --framer-input-padding: 12px; --framer-input-wrapper-height: auto; --framer-textarea-resize: vertical; flex: none; height: auto; min-height: 100px; position: relative; width: 100%; }',
	".framer-RDV60 .framer-18kmkf1-container { flex: none; height: 50px; position: relative; width: 100%; }",
	".framer-RDV60.framer-v-ngoxba.framer-t99dwh { width: 289px; }",
	".framer-RDV60.framer-v-ngoxba .framer-1a5caol { width: 285px; }",
	...css2,
	...css,
	'.framer-RDV60[data-border="true"]::after, .framer-RDV60 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerXNVvgS1rM = withCSS(Component, css3, "framer-RDV60");
var stdin_default2 = FramerXNVvgS1rM;
FramerXNVvgS1rM.displayName = "Cta Form Block";
FramerXNVvgS1rM.defaultProps = {
	height: 808,
	width: 520,
};
addPropertyControls(FramerXNVvgS1rM, {
	variant: {
		options: ["L2fQSkE_G", "SGW63zoAz", "bxatap7yZ"],
		optionTitles: ["Gray", "White", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerXNVvgS1rM,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
		...Button2Fonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta-form-block
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "bxatap7yZ",
	xl: "L2fQSkE_G",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFormBlockFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var cta_form_block_default = ComponentWithRoot;
export { cta_form_block_default as default };
