// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Large Desktop' | 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-QO5C2ULN.js";
import { stdin_default } from "./chunks/chunk-YFSXYVY3.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-EORJ2CEA.js";
import { className, css, fonts } from "./chunks/chunk-J7DO4Q5N.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:footer-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/y8ox0lEsqAEWqUCH2ELP/CXHnapHXhtpUrG1ukPkI/nn5WdxpJG.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/afmcnPDHlnaXcL5k9vgT/hluicf30DSKfMWF9RKh1/ioUCuBK7g.js
import { fontStore } from "unframer";
fontStore.loadWebFontsFromSelectors(["GF;Barlow-600"]);
var fonts2 = [
	{
		family: "Barlow",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/ioUCuBK7g:default",
			url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E30-8c4FAtlT47dw.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E30-8c4FAtlT47dw.ttf",
		weight: "600",
	},
];
var css2 = [
	'.framer-EUx9U .framer-styles-preset-1j8jxfd:not(.rich-text-wrapper), .framer-EUx9U .framer-styles-preset-1j8jxfd.rich-text-wrapper h6 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-weight: 600; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 991px) and (min-width: 0px) { .framer-EUx9U .framer-styles-preset-1j8jxfd:not(.rich-text-wrapper), .framer-EUx9U .framer-styles-preset-1j8jxfd.rich-text-wrapper h6 { --framer-font-family: "Barlow", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-weight: 600; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className2 = "framer-EUx9U";

// /:https://framerusercontent.com/modules/y8ox0lEsqAEWqUCH2ELP/CXHnapHXhtpUrG1ukPkI/nn5WdxpJG.js
var BrandLogoFonts = getFonts(stdin_default);
var FooterListItemFonts = getFonts(stdin_default2);
var SocialIconFonts = getFonts(stdin_default3);
var cycleOrder = ["att9duJ9Z", "RZVPgaSeD", "TaLBvpzpD", "kv3WAP34w"];
var serializationHash = "framer-TtoKQ";
var variantClassNames = {
	att9duJ9Z: "framer-v-44ahhj",
	kv3WAP34w: "framer-v-1rjk1zh",
	RZVPgaSeD: "framer-v-1r34p96",
	TaLBvpzpD: "framer-v-1r1jblu",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Large Desktop": "att9duJ9Z",
	Desktop: "RZVPgaSeD",
	Phone: "kv3WAP34w",
	Tablet: "TaLBvpzpD",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "att9duJ9Z",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "att9duJ9Z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-44ahhj",
							className3,
							classNames,
						)}
						data-framer-name={"Large Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"att9duJ9Z"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								kv3WAP34w: {
									"data-framer-name": "Phone",
								},
								RZVPgaSeD: {
									"data-framer-name": "Desktop",
								},
								TaLBvpzpD: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-xvipy7"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"hUWkt36e7"}
						>
							<motion.div
								className={"framer-1u3u5qc"}
								data-framer-name={"Footer Main Stack"}
								layoutDependency={layoutDependency}
								layoutId={"UKw_x3tvw"}
							>
								<motion.div
									className={"framer-1c2cpaa"}
									data-framer-name={"Footer Content Block"}
									layoutDependency={layoutDependency}
									layoutId={"EiWaGa1X7"}
								>
									<ComponentViewportProvider
										height={110}
										width={"166px"}
										y={
											(componentViewport?.y || 0) +
											130 +
											(((componentViewport?.height || 606) - 230 - 471) / 2 +
												0 +
												0) +
											0 +
											0 +
											35.5 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												kv3WAP34w: {
													y:
														(componentViewport?.y || 0) +
														60 +
														(((componentViewport?.height || 1003) -
															120 -
															1123) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												RZVPgaSeD: {
													y:
														(componentViewport?.y || 0) +
														100 +
														(((componentViewport?.height || 600) - 200 - 471) /
															2 +
															0 +
															0) +
														0 +
														0 +
														35.5 +
														0 +
														0,
												},
												TaLBvpzpD: {
													y:
														(componentViewport?.y || 0) +
														80 +
														(((componentViewport?.height || 608) - 160 - 471) /
															2 +
															0 +
															0) +
														0 +
														0 +
														35.5 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-qlz65o-container"}
											layoutDependency={layoutDependency}
											layoutId={"OOoaqZ18l-container"}
											nodeId={"OOoaqZ18l"}
											rendersWithMotion={true}
											scopeId={"nn5WdxpJG"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "OOoaqZ18l",
												layoutId: "OOoaqZ18l",
												style: {
													width: "100%",
												},
												variant: "fgAYltK0H",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-tx5zpq"}
										data-framer-name={"Footer Content Description"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"J__GuQTeE"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-636a3fe4-9f0f-4ae1-a43c-60a743a1245b, rgb(245, 242, 238))",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1sb8f1f"}
												data-styles-preset={"Clb2Z6A0U"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-636a3fe4-9f0f-4ae1-a43c-60a743a1245b, rgb(245, 242, 238)))",
												}}
											>
												{
													"Et historisk fjellhotell \u2013 helt for dere selv. Opplev roen i et levende luksushjem fra 1911, der dere disponerer hele huset og utsikten eksklusivt"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-b9thqo"}
									data-framer-name={"Footer List Block"}
									layoutDependency={layoutDependency}
									layoutId={"knqKvu5hg"}
								>
									<motion.div
										className={"framer-3ylydx"}
										data-framer-name={"Footer List Single"}
										layoutDependency={layoutDependency}
										layoutId={"Cc9EkEu3t"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-3iqucm"}
											data-framer-name={"Footer Title"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ZjvjE_Fbc"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-1j8jxfd"}
													data-styles-preset={"ioUCuBK7g"}
													style={{
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)))",
													}}
												>
													{"Utforsk"}
												</motion.h6>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-1w5k6en"}
											data-framer-name={"Footer List"}
											layoutDependency={layoutDependency}
											layoutId={"gHJWJX4YN"}
										>
											<Link
												href={{
													webPageId: "js50T9wbk",
												}}
												motionChild={true}
												nodeId={"aJwJy1UYP"}
												scopeId={"nn5WdxpJG"}
											>
												<motion.a
													className={"framer-bm9wqu framer-j5vadc"}
													data-framer-name={"Footer List Item Wrapper"}
													layoutDependency={layoutDependency}
													layoutId={"aJwJy1UYP"}
												>
													<ComponentViewportProvider
														height={72}
														width={`max(min(max(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) * 0.75 - 10px, 1px), 494px) * 0.1741, 1px)`}
														y={
															(componentViewport?.y || 0) +
															130 +
															(((componentViewport?.height || 606) -
																230 -
																471) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															61 +
															0 +
															0 +
															0
														}
														{...addPropertyOverrides(
															{
																kv3WAP34w: {
																	width: `max(min(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) * 0.971, 494px) * 0.3034, 1px)`,
																	y:
																		(componentViewport?.y || 0) +
																		60 +
																		(((componentViewport?.height || 1003) -
																			120 -
																			1123) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		280 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		0 +
																		0,
																},
																RZVPgaSeD: {
																	y:
																		(componentViewport?.y || 0) +
																		100 +
																		(((componentViewport?.height || 600) -
																			200 -
																			471) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		0 +
																		0,
																},
																TaLBvpzpD: {
																	width: `max(min(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) / 2.192, 494px) * 0.3034, 1px)`,
																	y:
																		(componentViewport?.y || 0) +
																		80 +
																		(((componentViewport?.height || 608) -
																			160 -
																			471) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		0 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-17xaisb-container"}
															layoutDependency={layoutDependency}
															layoutId={"HqvFAh3XC-container"}
															nodeId={"HqvFAh3XC"}
															rendersWithMotion={true}
															scopeId={"nn5WdxpJG"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "HqvFAh3XC",
																L5LTFJz6S: "hzVlWPAFe",
																layoutId: "HqvFAh3XC",
																style: {
																	width: "100%",
																},
																width: "100%",
																Z0GgWcXdb: "Historien",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												</motion.a>
											</Link>
											<Link
												href={{
													webPageId: "L3gNkOv2b",
												}}
												motionChild={true}
												nodeId={"cJSZEjaW6"}
												openInNewTab={false}
												scopeId={"nn5WdxpJG"}
											>
												<motion.a
													className={"framer-1f32vud framer-j5vadc"}
													data-framer-name={"Footer List Item Wrapper"}
													layoutDependency={layoutDependency}
													layoutId={"cJSZEjaW6"}
												>
													<ComponentViewportProvider
														height={72}
														width={`max(min(max(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) * 0.75 - 10px, 1px), 494px) * 0.1741, 1px)`}
														y={
															(componentViewport?.y || 0) +
															130 +
															(((componentViewport?.height || 606) -
																230 -
																471) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															61 +
															0 +
															88 +
															0
														}
														{...addPropertyOverrides(
															{
																kv3WAP34w: {
																	width: `max(min(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) * 0.971, 494px) * 0.3034, 1px)`,
																	y:
																		(componentViewport?.y || 0) +
																		60 +
																		(((componentViewport?.height || 1003) -
																			120 -
																			1123) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		280 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		88 +
																		0,
																},
																RZVPgaSeD: {
																	y:
																		(componentViewport?.y || 0) +
																		100 +
																		(((componentViewport?.height || 600) -
																			200 -
																			471) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		88 +
																		0,
																},
																TaLBvpzpD: {
																	width: `max(min(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) / 2.192, 494px) * 0.3034, 1px)`,
																	y:
																		(componentViewport?.y || 0) +
																		80 +
																		(((componentViewport?.height || 608) -
																			160 -
																			471) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		88 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-fldd7y-container"}
															layoutDependency={layoutDependency}
															layoutId={"vjq1RNVTf-container"}
															nodeId={"vjq1RNVTf"}
															rendersWithMotion={true}
															scopeId={"nn5WdxpJG"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "vjq1RNVTf",
																L5LTFJz6S: "hzVlWPAFe",
																layoutId: "vjq1RNVTf",
																style: {
																	width: "100%",
																},
																width: "100%",
																Z0GgWcXdb: "Booking",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												</motion.a>
											</Link>
											<Link
												href={{
													webPageId: "GZxH1Y62Q",
												}}
												motionChild={true}
												nodeId={"cbBZBFyJD"}
												scopeId={"nn5WdxpJG"}
											>
												<motion.a
													className={"framer-ozal1s framer-j5vadc"}
													data-framer-name={"Footer List Item Wrapper"}
													layoutDependency={layoutDependency}
													layoutId={"cbBZBFyJD"}
												>
													<ComponentViewportProvider
														height={72}
														width={`max(min(max(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) * 0.75 - 10px, 1px), 494px) * 0.1741, 1px)`}
														y={
															(componentViewport?.y || 0) +
															130 +
															(((componentViewport?.height || 606) -
																230 -
																471) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															61 +
															0 +
															176 +
															0
														}
														{...addPropertyOverrides(
															{
																kv3WAP34w: {
																	width: `max(min(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) * 0.971, 494px) * 0.3034, 1px)`,
																	y:
																		(componentViewport?.y || 0) +
																		60 +
																		(((componentViewport?.height || 1003) -
																			120 -
																			1123) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		280 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		176 +
																		0,
																},
																RZVPgaSeD: {
																	y:
																		(componentViewport?.y || 0) +
																		100 +
																		(((componentViewport?.height || 600) -
																			200 -
																			471) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		176 +
																		0,
																},
																TaLBvpzpD: {
																	width: `max(min(min(min(${componentViewport?.width || "100vw"}, 1356px) - 60px, 1162px) / 2.192, 494px) * 0.3034, 1px)`,
																	y:
																		(componentViewport?.y || 0) +
																		80 +
																		(((componentViewport?.height || 608) -
																			160 -
																			471) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		61 +
																		0 +
																		176 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-ryuayy-container"}
															layoutDependency={layoutDependency}
															layoutId={"tU38ea6EU-container"}
															nodeId={"tU38ea6EU"}
															rendersWithMotion={true}
															scopeId={"nn5WdxpJG"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "tU38ea6EU",
																L5LTFJz6S: "hzVlWPAFe",
																layoutId: "tU38ea6EU",
																style: {
																	width: "100%",
																},
																width: "100%",
																Z0GgWcXdb: "Kontakt oss",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												</motion.a>
											</Link>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-wtm1uj"}
										data-framer-name={"Footer List Single"}
										layoutDependency={layoutDependency}
										layoutId={"FBg9jNkZF"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-15w3u2k"}
											data-framer-name={"Footer Title"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"VA1KNBbuF"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-1j8jxfd"}
													data-styles-preset={"ioUCuBK7g"}
													style={{
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)))",
													}}
												>
													{"Kontakt"}
												</motion.h6>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-z5yhsd"}
											data-framer-name={"Footer List"}
											layoutDependency={layoutDependency}
											layoutId={"SlBVijdKz"}
										>
											<ComponentViewportProvider
												height={72}
												width={"211px"}
												y={
													(componentViewport?.y || 0) +
													130 +
													(((componentViewport?.height || 606) - 230 - 471) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0 +
													0 +
													63 +
													0 +
													0
												}
												{...addPropertyOverrides(
													{
														kv3WAP34w: {
															y:
																(componentViewport?.y || 0) +
																60 +
																(((componentViewport?.height || 1003) -
																	120 -
																	1123) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																280 +
																0 +
																309 +
																20 +
																63 +
																0 +
																0,
														},
														RZVPgaSeD: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 600) -
																	200 -
																	471) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																63 +
																0 +
																0,
														},
														TaLBvpzpD: {
															y:
																(componentViewport?.y || 0) +
																80 +
																(((componentViewport?.height || 608) -
																	160 -
																	471) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																63 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-kldyog-container"}
													layoutDependency={layoutDependency}
													layoutId={"NB2eAYRQy-container"}
													nodeId={"NB2eAYRQy"}
													rendersWithMotion={true}
													scopeId={"nn5WdxpJG"}
												>
													{_jsx(stdin_default2, {
														height: "100%",
														id: "NB2eAYRQy",
														L5LTFJz6S: "gpLff6OSv",
														layoutId: "NB2eAYRQy",
														style: {
															width: "100%",
														},
														width: "100%",
														Z0GgWcXdb:
															"Fjellheimen Hotell Bygdinvegen 3036, 2950 Skammestein",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider
												height={72}
												width={"249px"}
												y={
													(componentViewport?.y || 0) +
													130 +
													(((componentViewport?.height || 606) - 230 - 471) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0 +
													0 +
													63 +
													0 +
													88
												}
												{...addPropertyOverrides(
													{
														kv3WAP34w: {
															y:
																(componentViewport?.y || 0) +
																60 +
																(((componentViewport?.height || 1003) -
																	120 -
																	1123) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																280 +
																0 +
																309 +
																20 +
																63 +
																0 +
																88,
														},
														RZVPgaSeD: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 600) -
																	200 -
																	471) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																63 +
																0 +
																88,
														},
														TaLBvpzpD: {
															y:
																(componentViewport?.y || 0) +
																80 +
																(((componentViewport?.height || 608) -
																	160 -
																	471) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																63 +
																0 +
																88,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1cw2y2h-container"}
													layoutDependency={layoutDependency}
													layoutId={"Xa7M1FWgo-container"}
													nodeId={"Xa7M1FWgo"}
													rendersWithMotion={true}
													scopeId={"nn5WdxpJG"}
												>
													{_jsx(stdin_default2, {
														height: "100%",
														id: "Xa7M1FWgo",
														L5LTFJz6S: "xLEgszbjQ",
														layoutId: "Xa7M1FWgo",
														style: {
															width: "100%",
														},
														width: "100%",
														Z0GgWcXdb: "fjellheimenhotell@gmail.com",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider
												height={72}
												width={"211px"}
												y={
													(componentViewport?.y || 0) +
													130 +
													(((componentViewport?.height || 606) - 230 - 471) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0 +
													0 +
													63 +
													0 +
													176
												}
												{...addPropertyOverrides(
													{
														kv3WAP34w: {
															y:
																(componentViewport?.y || 0) +
																60 +
																(((componentViewport?.height || 1003) -
																	120 -
																	1123) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																280 +
																0 +
																309 +
																20 +
																63 +
																0 +
																176,
														},
														RZVPgaSeD: {
															y:
																(componentViewport?.y || 0) +
																100 +
																(((componentViewport?.height || 600) -
																	200 -
																	471) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																63 +
																0 +
																176,
														},
														TaLBvpzpD: {
															y:
																(componentViewport?.y || 0) +
																80 +
																(((componentViewport?.height || 608) -
																	160 -
																	471) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																63 +
																0 +
																176,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1f2qfws-container"}
													layoutDependency={layoutDependency}
													layoutId={"JDB8xxPJV-container"}
													nodeId={"JDB8xxPJV"}
													rendersWithMotion={true}
													scopeId={"nn5WdxpJG"}
												>
													{_jsx(stdin_default2, {
														height: "100%",
														id: "JDB8xxPJV",
														L5LTFJz6S: "AWCYocEdb",
														layoutId: "JDB8xxPJV",
														style: {
															width: "100%",
														},
														width: "100%",
														Z0GgWcXdb: "+47 988 07 242",
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-gg5wli"}
								data-border={true}
								data-framer-name={"Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"wpLlpVjie"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color":
										"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56))",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "1px",
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-84kxu5"}
									data-framer-name={
										"\xA9 2023 All Right Reserved by FramerBite"
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"yiQOUrISY"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1sb8f1f"}
											data-styles-preset={"Clb2Z6A0U"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)))",
											}}
										>
											{"\xA9 2026 All Right Reserved. Coupler Oslo AS."}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-2t5w25"}
									data-framer-name={"Social Icons"}
									layoutDependency={layoutDependency}
									layoutId={"xuDG6ejp0"}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1daps9w-container"}
											layoutDependency={layoutDependency}
											layoutId={"u0i3CqMEK-container"}
											nodeId={"u0i3CqMEK"}
											rendersWithMotion={true}
											scopeId={"nn5WdxpJG"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												icons: "eq1w4LqdE",
												id: "u0i3CqMEK",
												layoutId: "u0i3CqMEK",
												link: "facebook.com",
												style: {
													height: "100%",
													width: "100%",
												},
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-nhd9pm-container"}
											layoutDependency={layoutDependency}
											layoutId={"r3IscpahB-container"}
											nodeId={"r3IscpahB"}
											rendersWithMotion={true}
											scopeId={"nn5WdxpJG"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												icons: "d52aWdq99",
												id: "r3IscpahB",
												layoutId: "r3IscpahB",
												link: "skype.com",
												style: {
													height: "100%",
													width: "100%",
												},
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-jeijqj-container"}
											layoutDependency={layoutDependency}
											layoutId={"VVV2xAMF5-container"}
											nodeId={"VVV2xAMF5"}
											rendersWithMotion={true}
											scopeId={"nn5WdxpJG"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												icons: "f_UKCfQLw",
												id: "VVV2xAMF5",
												layoutId: "VVV2xAMF5",
												link: "twitter.com",
												style: {
													height: "100%",
													width: "100%",
												},
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-1j3cwzf-container"}
											layoutDependency={layoutDependency}
											layoutId={"aw4LnNTat-container"}
											nodeId={"aw4LnNTat"}
											rendersWithMotion={true}
											scopeId={"nn5WdxpJG"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												icons: "AgIMbZju9",
												id: "aw4LnNTat",
												layoutId: "aw4LnNTat",
												link: "linkedin.com",
												style: {
													height: "100%",
													width: "100%",
												},
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TtoKQ.framer-j5vadc, .framer-TtoKQ .framer-j5vadc { display: block; }",
	".framer-TtoKQ.framer-44ahhj { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 130px 0px 100px 0px; position: relative; width: 1440px; }",
	".framer-TtoKQ .framer-xvipy7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 72px; height: min-content; justify-content: center; max-width: 1356px; overflow: visible; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
	".framer-TtoKQ .framer-1u3u5qc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1162px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TtoKQ .framer-1c2cpaa { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 282px; overflow: visible; padding: 0px; position: relative; width: 25%; }",
	".framer-TtoKQ .framer-qlz65o-container { flex: none; height: auto; position: relative; width: 166px; }",
	".framer-TtoKQ .framer-tx5zpq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-TtoKQ .framer-b9thqo { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 494px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-TtoKQ .framer-3ylydx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 34px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 17%; }",
	".framer-TtoKQ .framer-3iqucm, .framer-TtoKQ .framer-15w3u2k, .framer-TtoKQ .framer-84kxu5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-TtoKQ .framer-1w5k6en { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TtoKQ .framer-bm9wqu, .framer-TtoKQ .framer-1f32vud, .framer-TtoKQ .framer-ozal1s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-TtoKQ .framer-17xaisb-container, .framer-TtoKQ .framer-fldd7y-container, .framer-TtoKQ .framer-ryuayy-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-TtoKQ .framer-wtm1uj { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 51%; }",
	".framer-TtoKQ .framer-z5yhsd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TtoKQ .framer-kldyog-container, .framer-TtoKQ .framer-1f2qfws-container { flex: none; height: auto; position: relative; width: 211px; }",
	".framer-TtoKQ .framer-1cw2y2h-container { flex: none; height: auto; position: relative; width: 249px; }",
	".framer-TtoKQ .framer-gg5wli { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 60px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-TtoKQ .framer-2t5w25 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 11.38px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TtoKQ .framer-1daps9w-container, .framer-TtoKQ .framer-nhd9pm-container, .framer-TtoKQ .framer-jeijqj-container, .framer-TtoKQ .framer-1j3cwzf-container { flex: none; height: 28px; position: relative; width: 28px; }",
	".framer-TtoKQ.framer-v-1r34p96.framer-44ahhj { padding: 100px 0px 100px 0px; width: 992px; }",
	".framer-TtoKQ.framer-v-1r34p96 .framer-2t5w25, .framer-TtoKQ.framer-v-1r1jblu .framer-2t5w25, .framer-TtoKQ.framer-v-1rjk1zh .framer-2t5w25 { gap: 10px; }",
	".framer-TtoKQ.framer-v-1r1jblu.framer-44ahhj { padding: 80px 0px 80px 0px; width: 768px; }",
	".framer-TtoKQ.framer-v-1r1jblu .framer-b9thqo { flex: none; width: 46%; }",
	".framer-TtoKQ.framer-v-1r1jblu .framer-3ylydx, .framer-TtoKQ.framer-v-1rjk1zh .framer-3ylydx { order: 0; width: 30%; }",
	".framer-TtoKQ.framer-v-1r1jblu .framer-wtm1uj { order: 1; width: 58%; }",
	".framer-TtoKQ.framer-v-1rjk1zh.framer-44ahhj { padding: 60px 0px 60px 0px; width: 370px; }",
	".framer-TtoKQ.framer-v-1rjk1zh .framer-1u3u5qc { flex-direction: column; gap: 40px; justify-content: center; }",
	".framer-TtoKQ.framer-v-1rjk1zh .framer-1c2cpaa { width: 73%; }",
	".framer-TtoKQ.framer-v-1rjk1zh .framer-b9thqo { flex: none; flex-direction: column; width: 97%; }",
	".framer-TtoKQ.framer-v-1rjk1zh .framer-wtm1uj { order: 1; padding: 20px 0px 0px 0px; width: 58%; }",
	".framer-TtoKQ.framer-v-1rjk1zh .framer-gg5wli { flex-direction: column; gap: 19px; justify-content: flex-start; }",
	...css,
	...css2,
	'.framer-TtoKQ[data-border="true"]::after, .framer-TtoKQ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framernn5WdxpJG = withCSS(Component, css3, "framer-TtoKQ");
var stdin_default4 = Framernn5WdxpJG;
Framernn5WdxpJG.displayName = "Footer Section";
Framernn5WdxpJG.defaultProps = {
	height: 606,
	width: 1440,
};
addPropertyControls(Framernn5WdxpJG, {
	variant: {
		options: ["att9duJ9Z", "RZVPgaSeD", "TaLBvpzpD", "kv3WAP34w"],
		optionTitles: ["Large Desktop", "Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framernn5WdxpJG,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BrandLogoFonts,
		...FooterListItemFonts,
		...SocialIconFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "kv3WAP34w",
	md: "TaLBvpzpD",
	lg: "RZVPgaSeD",
	xl: "att9duJ9Z",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var footer_section_default = ComponentWithRoot;
export { footer_section_default as default };
