// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Desktop' | 'Phone' | 'Tablet' | 'Primary White' | 'Desktop White' // Variant
 * background?: string // Background
}} Props

 */
import { stdin_default } from "./chunks/chunk-GTUI6HAM.js";
import "./chunks/chunk-I7NQ2SSX.js";
import "./chunks/chunk-YFSXYVY3.js";
import "./chunks/chunk-WZBDU7EE.js";
import "./chunks/chunk-DNUD7TZ6.js";
import "./chunks/chunk-UQLTEEAL.js";
import "./chunks/chunk-KD6F3UC3.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6LlkVF1VgpkFXZHqy08h/pRoi8meLuHKj9Eu9te2q/Lkm2phrfD.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var HeaderNavbarFonts = getFonts(stdin_default);
var cycleOrder = [
	"e_HXWpS83",
	"ejArW8x7M",
	"jUpDAc6Fr",
	"WUU5SChyt",
	"m0I4KQTxC",
	"J7bQ6B9vR",
];
var serializationHash = "framer-LQprF";
var variantClassNames = {
	e_HXWpS83: "framer-v-1if5unm",
	ejArW8x7M: "framer-v-y225qg",
	J7bQ6B9vR: "framer-v-5vo5xv",
	jUpDAc6Fr: "framer-v-936btv",
	m0I4KQTxC: "framer-v-48c406",
	WUU5SChyt: "framer-v-zdfrq0",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop White": "J7bQ6B9vR",
	"Primary White": "m0I4KQTxC",
	Default: "e_HXWpS83",
	Desktop: "ejArW8x7M",
	Phone: "jUpDAc6Fr",
	Tablet: "WUU5SChyt",
};
var getProps = ({ background, height, id, width, ...props }) => {
	return {
		...props,
		lSFZjaZ4m: background ?? props.lSFZjaZ4m ?? "rgba(27, 27, 27, 0)",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "e_HXWpS83",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		lSFZjaZ4m: lSFZjaZ4m2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "e_HXWpS83",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1if5unm",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"e_HXWpS83"}
						ref={refBinding}
						style={{
							backdropFilter: "none",
							backgroundColor: lSFZjaZ4m2,
							WebkitBackdropFilter: "none",
							...style,
						}}
						variants={{
							J7bQ6B9vR: {
								backdropFilter: "none",
								backgroundColor:
									"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
								WebkitBackdropFilter: "none",
							},
							m0I4KQTxC: {
								backdropFilter: "blur(7px)",
								backgroundColor: "rgba(255, 255, 255, 0.91)",
								WebkitBackdropFilter: "blur(7px)",
							},
						}}
						{...addPropertyOverrides(
							{
								ejArW8x7M: {
									"data-framer-name": "Desktop",
								},
								J7bQ6B9vR: {
									"data-framer-name": "Desktop White",
								},
								jUpDAc6Fr: {
									"data-framer-name": "Phone",
								},
								m0I4KQTxC: {
									"data-framer-name": "Primary White",
								},
								WUU5SChyt: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-16jshna"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"gqRXRIUm9"}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backgroundColor: "rgba(0, 0, 0, 0)",
							}}
							variants={{
								J7bQ6B9vR: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
								jUpDAc6Fr: {
									"--border-bottom-width": "1px",
									"--border-color": "rgb(255, 255, 255)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgba(255, 255, 255, 0.8)",
								},
								m0I4KQTxC: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
								WUU5SChyt: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
							}}
							{...addPropertyOverrides(
								{
									jUpDAc6Fr: {
										"data-border": true,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<ComponentViewportProvider
								height={110}
								width={`calc(max(${componentViewport?.width || "100vw"}, 1px) - 60px)`}
								y={
									(componentViewport?.y || 0) +
									(0 + ((componentViewport?.height || 200) - 0 - 118) / 2) +
									8 +
									0
								}
								{...addPropertyOverrides(
									{
										ejArW8x7M: {
											y:
												(componentViewport?.y || 0) +
												(0 +
													((componentViewport?.height || 95.5) - 0 - 126) / 2) +
												8 +
												0,
										},
										J7bQ6B9vR: {
											y:
												(componentViewport?.y || 0) +
												(0 +
													((componentViewport?.height || 95.5) - 0 - 126) / 2) +
												8 +
												0,
										},
										jUpDAc6Fr: {
											width: `calc(min(max(${componentViewport?.width || "100vw"}, 1px), 520px) - 24px)`,
											y:
												(componentViewport?.y || 0) +
												(0 +
													((componentViewport?.height || 111.5) - 0 - 118) /
														2) +
												8 +
												0,
										},
										m0I4KQTxC: {
											y:
												(componentViewport?.y || 0) +
												(0 +
													((componentViewport?.height || 200) - 0 - 126) / 2) +
												8 +
												0,
										},
										WUU5SChyt: {
											width: `calc(min(max(${componentViewport?.width || "100vw"}, 1px), 720px) - 60px)`,
											y:
												(componentViewport?.y || 0) +
												(0 +
													((componentViewport?.height || 127.5) - 0 - 118) /
														2) +
												8 +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1drvwqm-container"}
									layoutDependency={layoutDependency}
									layoutId={"pSbiQfxPI-container"}
									nodeId={"pSbiQfxPI"}
									rendersWithMotion={true}
									scopeId={"Lkm2phrfD"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "pSbiQfxPI",
										layoutId: "pSbiQfxPI",
										style: {
											width: "100%",
										},
										variant: "UKQCb8n5o",
										width: "100%",
										...addPropertyOverrides(
											{
												ejArW8x7M: {
													variant: "kw0QVEKY4",
												},
												J7bQ6B9vR: {
													variant: "xGeKbM2lB",
												},
												jUpDAc6Fr: {
													variant: "tdZbw3o8Y",
												},
												m0I4KQTxC: {
													variant: "unFe5QdzP",
												},
												WUU5SChyt: {
													variant: "VtZ2cH9kD",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-LQprF.framer-1kqi9c4, .framer-LQprF .framer-1kqi9c4 { display: block; }",
	".framer-LQprF.framer-1if5unm { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 1440px; }",
	".framer-LQprF .framer-16jshna { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 30px 0px 30px; position: relative; width: 1px; }",
	".framer-LQprF .framer-1drvwqm-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-LQprF.framer-v-y225qg.framer-1if5unm, .framer-LQprF.framer-v-5vo5xv.framer-1if5unm { width: 1200px; }",
	".framer-LQprF.framer-v-y225qg .framer-16jshna, .framer-LQprF.framer-v-48c406 .framer-16jshna, .framer-LQprF.framer-v-5vo5xv .framer-16jshna { padding: 8px 30px 8px 30px; }",
	".framer-LQprF.framer-v-936btv.framer-1if5unm { width: 400px; }",
	".framer-LQprF.framer-v-936btv .framer-16jshna { max-width: 520px; padding: 8px 12px 0px 12px; }",
	".framer-LQprF.framer-v-zdfrq0.framer-1if5unm { width: 800px; }",
	".framer-LQprF.framer-v-zdfrq0 .framer-16jshna { max-width: 720px; }",
	'.framer-LQprF[data-border="true"]::after, .framer-LQprF [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerLkm2phrfD = withCSS(Component, css, "framer-LQprF");
var stdin_default2 = FramerLkm2phrfD;
FramerLkm2phrfD.displayName = "Header";
FramerLkm2phrfD.defaultProps = {
	height: 118,
	width: 1440,
};
addPropertyControls(FramerLkm2phrfD, {
	variant: {
		options: [
			"e_HXWpS83",
			"ejArW8x7M",
			"jUpDAc6Fr",
			"WUU5SChyt",
			"m0I4KQTxC",
			"J7bQ6B9vR",
		],
		optionTitles: [
			"Default",
			"Desktop",
			"Phone",
			"Tablet",
			"Primary White",
			"Desktop White",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	lSFZjaZ4m: {
		defaultValue: "rgba(27, 27, 27, 0)",
		title: "Background",
		type: ControlType.Color,
	},
});
addFonts(
	FramerLkm2phrfD,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...HeaderNavbarFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "WUU5SChyt",
	lg: "ejArW8x7M",
	xl: "e_HXWpS83",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var header_default = ComponentWithRoot;
export { header_default as default };
