// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Desktop ' | 'Tablet' | 'Tablet - Open' | 'Phone' | 'Phone - Open' | 'Default - Hover' | 'Default - Open' | 'Primary White' | 'Primary White Hover' | 'Primary White Hover Open' | 'Desktop Hover' | 'Desktop Hover Open' | 'Desktop White' | 'Desktop Hover White' | 'Desktop White Hover Open' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-GTUI6HAM.js";
import "./chunks/chunk-I7NQ2SSX.js";
import "./chunks/chunk-YFSXYVY3.js";
import "./chunks/chunk-WZBDU7EE.js";
import "./chunks/chunk-DNUD7TZ6.js";
import "./chunks/chunk-UQLTEEAL.js";
import "./chunks/chunk-KD6F3UC3.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:header-navbar
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "tdZbw3o8Y",
	md: "VtZ2cH9kD",
	xl: "UKQCb8n5o",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderNavbarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var header_navbar_default = ComponentWithRoot;
export { header_navbar_default as default };
