// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Small Card' | 'Medium' | 'Large' | 'Mobile' // Variant
 * title?: string // Title
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * subtitle?: string // Subtitle
}} Props

 */
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:image-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/n0JBTTn09X1VCAOSWzfd/DhUCtR9ctcrSqbMbXbdn/WWsjZc5eB.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	K7lqlBMJg: {
		hover: true,
	},
	o6H7Qvsbl: {
		hover: true,
	},
	YIMfeUqrr: {
		hover: true,
	},
};
var cycleOrder = ["YIMfeUqrr", "K7lqlBMJg", "o6H7Qvsbl", "HtdRecbY7"];
var serializationHash = "framer-e9eNA";
var variantClassNames = {
	HtdRecbY7: "framer-v-1084r7o",
	K7lqlBMJg: "framer-v-8aiofm",
	o6H7Qvsbl: "framer-v-1nsjioy",
	YIMfeUqrr: "framer-v-1f7f75l",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Small Card": "YIMfeUqrr",
	Large: "o6H7Qvsbl",
	Medium: "K7lqlBMJg",
	Mobile: "HtdRecbY7",
};
var getProps = ({ height, id, image, subtitle, title, width, ...props }) => {
	return {
		...props,
		dBZe7S4Tt: title ?? props.dBZe7S4Tt ?? "Double Room",
		l5ZZO2Tc5: image ??
			props.l5ZZO2Tc5 ?? {
				pixelHeight: 2048,
				pixelWidth: 4096,
				src: "https://framerusercontent.com/images/Sl9Z8FMRbGhYBJnwYGY1Hy8vToE.jpg?scale-down-to=512&width=4096&height=2048",
				srcSet:
					"https://framerusercontent.com/images/Sl9Z8FMRbGhYBJnwYGY1Hy8vToE.jpg?scale-down-to=512&width=4096&height=2048 512w,https://framerusercontent.com/images/Sl9Z8FMRbGhYBJnwYGY1Hy8vToE.jpg?scale-down-to=1024&width=4096&height=2048 1024w,https://framerusercontent.com/images/Sl9Z8FMRbGhYBJnwYGY1Hy8vToE.jpg?scale-down-to=2048&width=4096&height=2048 2048w,https://framerusercontent.com/images/Sl9Z8FMRbGhYBJnwYGY1Hy8vToE.jpg?width=4096&height=2048 4096w",
			},
		NeSY72sOE: subtitle ?? props.NeSY72sOE ?? "Room",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "YIMfeUqrr",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		dBZe7S4Tt,
		l5ZZO2Tc5,
		NeSY72sOE,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YIMfeUqrr",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1f7f75l",
							className,
							classNames,
						)}
						data-framer-name={"Small Card"}
						layoutDependency={layoutDependency}
						layoutId={"YIMfeUqrr"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							...style,
						}}
						variants={{
							"o6H7Qvsbl-hover": {
								backgroundColor:
									"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
							},
							"YIMfeUqrr-hover": {
								backgroundColor: "rgba(0, 0, 0, 0)",
							},
						}}
						{...addPropertyOverrides(
							{
								"K7lqlBMJg-hover": {
									"data-framer-name": void 0,
								},
								"o6H7Qvsbl-hover": {
									"data-framer-name": void 0,
								},
								"YIMfeUqrr-hover": {
									"data-framer-name": void 0,
								},
								HtdRecbY7: {
									"data-framer-name": "Mobile",
								},
								K7lqlBMJg: {
									"data-framer-name": "Medium",
								},
								o6H7Qvsbl: {
									"data-framer-name": "Large",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1e1kpum"}
							data-framer-name={"Hover Block"}
							layoutDependency={layoutDependency}
							layoutId={"uKUn2Okmz"}
							style={{
								backgroundColor: "rgba(0, 0, 0, 0)",
								opacity: 0,
							}}
							variants={{
								"K7lqlBMJg-hover": {
									opacity: 1,
								},
								"o6H7Qvsbl-hover": {
									opacity: 1,
								},
								"YIMfeUqrr-hover": {
									backgroundColor:
										"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
									opacity: 1,
								},
								HtdRecbY7: {
									backgroundColor:
										"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
									opacity: 1,
								},
								K7lqlBMJg: {
									backgroundColor:
										"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
								},
								o6H7Qvsbl: {
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
							}}
						>
							<motion.div
								className={"framer-1mcfr7"}
								data-border={true}
								data-framer-name={"Hover Text Block"}
								layoutDependency={layoutDependency}
								layoutId={"zOunKnXFV"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor:
										"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
								}}
								variants={{
									HtdRecbY7: {
										"--border-bottom-width": "0px",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-top-width": "0px",
									},
								}}
								{...addPropertyOverrides(
									{
										HtdRecbY7: {
											transformTemplate: transformTemplate1,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-q0grss"}
									data-framer-name={"Title "}
									fonts={["GF;Playfair Display-500"]}
									layoutDependency={layoutDependency}
									layoutId={"WxyUOtQbS"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27))",
									}}
									text={dBZe7S4Tt}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7UGxheWZhaXIgRGlzcGxheS01MDA=",
												"--framer-font-family":
													'"Playfair Display", "Playfair Display Placeholder", serif',
												"--framer-font-size": "24px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.5px",
												"--framer-line-height": "140%",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)))",
											}}
										>
											{"Double Room"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-xbzhkv"}
									data-framer-name={"Subtitle"}
									fonts={["GF;Barlow-500"]}
									layoutDependency={layoutDependency}
									layoutId={"pkHay12b4"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e29b414e-778b-4330-a92f-715c64d82d8a, rgb(166, 163, 160))",
									}}
									text={NeSY72sOE}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7QmFybG93LTUwMA==",
												"--framer-font-family":
													'"Barlow", "Barlow Placeholder", sans-serif',
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "0px",
												"--framer-line-height": "150%",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e29b414e-778b-4330-a92f-715c64d82d8a, rgb(166, 163, 160)))",
											}}
										>
											{"Room"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 320) * 0.5000000000000002 -
											(((componentViewport?.height || 320) - 0) * 1) / 2),
								),
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(l5ZZO2Tc5),
							}}
							className={"framer-n8nb4c"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"LpWV2HRWp"}
							style={{
								opacity: 1,
							}}
							variants={{
								"K7lqlBMJg-hover": {
									opacity: 0,
								},
								"o6H7Qvsbl-hover": {
									opacity: 0,
								},
								"YIMfeUqrr-hover": {
									opacity: 0,
								},
							}}
							{...addPropertyOverrides(
								{
									HtdRecbY7: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 273) / 2 +
														0 +
														0),
											),
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(l5ZZO2Tc5),
										},
									},
									K7lqlBMJg: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													((componentViewport?.height || 431) *
														0.5000000000000002 -
														(((componentViewport?.height || 431) - 0) * 1) / 2),
											),
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(l5ZZO2Tc5),
										},
									},
									o6H7Qvsbl: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													((componentViewport?.height || 751) *
														0.5000000000000002 -
														(((componentViewport?.height || 751) - 0) * 1) / 2),
											),
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(l5ZZO2Tc5),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-e9eNA.framer-tpj3cm, .framer-e9eNA .framer-tpj3cm { display: block; }",
	".framer-e9eNA.framer-1f7f75l { cursor: pointer; height: 320px; overflow: hidden; position: relative; width: 400px; }",
	".framer-e9eNA .framer-1e1kpum { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 0px; position: absolute; top: 0px; width: 100%; }",
	".framer-e9eNA .framer-1mcfr7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-e9eNA .framer-q0grss, .framer-e9eNA .framer-xbzhkv { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-e9eNA .framer-n8nb4c { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; }",
	".framer-e9eNA.framer-v-8aiofm.framer-1f7f75l { aspect-ratio: 0.9280742459396751 / 1; height: var(--framer-aspect-ratio-supported, 431px); }",
	".framer-e9eNA.framer-v-1nsjioy.framer-1f7f75l { aspect-ratio: 0.5326231691078562 / 1; height: var(--framer-aspect-ratio-supported, 751px); }",
	".framer-e9eNA.framer-v-1nsjioy .framer-1e1kpum { bottom: -751px; height: unset; }",
	".framer-e9eNA.framer-v-1084r7o.framer-1f7f75l { align-content: center; align-items: center; cursor: unset; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px; }",
	".framer-e9eNA.framer-v-1084r7o .framer-1e1kpum { height: min-content; left: unset; min-height: 118px; order: 1; position: relative; top: unset; }",
	".framer-e9eNA.framer-v-1084r7o .framer-1mcfr7 { height: min-content; left: 50%; top: 50%; }",
	".framer-e9eNA.framer-v-1084r7o .framer-n8nb4c { aspect-ratio: 1.465201465201465 / 1; height: var(--framer-aspect-ratio-supported, 137px); left: unset; order: 0; position: relative; top: unset; }",
	".framer-e9eNA.framer-v-8aiofm.hover .framer-1e1kpum { padding: 22px; }",
	".framer-e9eNA.framer-v-8aiofm.hover .framer-1mcfr7, .framer-e9eNA.framer-v-1f7f75l.hover .framer-1mcfr7 { flex: 1 0 0px; height: 1px; left: unset; position: relative; top: unset; z-index: 10; }",
	".framer-e9eNA.framer-v-1nsjioy.hover .framer-1e1kpum { bottom: unset; height: 100%; padding: 22px; }",
	".framer-e9eNA.framer-v-1nsjioy.hover .framer-1mcfr7 { flex: 1 0 0px; height: 1px; left: unset; position: relative; top: unset; }",
	".framer-e9eNA.framer-v-1f7f75l.hover.framer-1f7f75l { aspect-ratio: 1.25 / 1; height: var(--framer-aspect-ratio-supported, 320px); }",
	".framer-e9eNA.framer-v-1f7f75l.hover .framer-1e1kpum { padding: 22px; z-index: 0; }",
	'.framer-e9eNA[data-border="true"]::after, .framer-e9eNA [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerWWsjZc5eB = withCSS(Component, css, "framer-e9eNA");
var stdin_default = FramerWWsjZc5eB;
FramerWWsjZc5eB.displayName = "Image Card";
FramerWWsjZc5eB.defaultProps = {
	height: 320,
	width: 400,
};
addPropertyControls(FramerWWsjZc5eB, {
	variant: {
		options: ["YIMfeUqrr", "K7lqlBMJg", "o6H7Qvsbl", "HtdRecbY7"],
		optionTitles: ["Small Card", "Medium", "Large", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	dBZe7S4Tt: {
		defaultValue: "Double Room",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	l5ZZO2Tc5: {
		__defaultAssetReference:
			"data:framer/asset-reference,Sl9Z8FMRbGhYBJnwYGY1Hy8vToE.jpg?originalFilename=Image.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	NeSY72sOE: {
		defaultValue: "Room",
		displayTextArea: false,
		title: "Subtitle",
		type: ControlType.String,
	},
});
addFonts(
	FramerWWsjZc5eB,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Playfair Display",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/playfairdisplay/v39/nuFvD-vYSZviVYUb_rj3ij__anPXJzDwcbmjWBN2PKd3vUDVZNLo_U2r.woff2",
					weight: "500",
				},
				{
					family: "Barlow",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E3_-gc5VAtlT47dw.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:image-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HtdRecbY7",
	xl: "K7lqlBMJg",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImageCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var image_card_default = ComponentWithRoot;
export { image_card_default as default };
