// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * mouseEnter?: Function // Mouse Enter
 * mouseLeave?: Function // Mouse Leave
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-UQLTEEAL.js";
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:mega-menu
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/uFKJgyipEBxFt5UllyiV/BoDOJwURuaCQbMwXA9Vz/nrNEBm02s.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	resolveLink,
	useActiveVariantCallback as useActiveVariantCallback2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/iAqeCQIr64vRRU7nZtCn/SLAZE1Sc6JmCvAVC8g9I/pmUQ8lmqr.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	Link,
	RichText,
	useActiveVariantCallback,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MaterialFonts = getFonts(Icon);
var enabledGestures = {
	aGHAagPp0: {
		hover: true,
	},
	oFZUur6Pc: {
		hover: true,
	},
};
var cycleOrder = ["aGHAagPp0", "oFZUur6Pc"];
var variantClassNames = {
	aGHAagPp0: "framer-v-14fg6c9",
	oFZUur6Pc: "framer-v-1ug7wbl",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1.2,
		stiffness: 300,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Menu - Mega": "oFZUur6Pc",
	"Variant 1": "aGHAagPp0",
};
var getProps = ({
	arrow,
	arrowColor,
	color,
	height,
	id,
	link,
	tap,
	title,
	width,
	...props
}) => {
	var ref, ref1, ref2, _variant, ref3;
	return {
		...props,
		EARkE2sZA:
			(ref =
				arrowColor !== null && arrowColor !== void 0
					? arrowColor
					: props.EARkE2sZA) !== null && ref !== void 0
				? ref
				: 'var(--token-1f2d55b1-7509-480d-9086-134655dcd9c7, rgb(17, 17, 17)) /* {"name":"Neutral / 07"} */',
		j_KE4sm_E: arrow !== null && arrow !== void 0 ? arrow : props.j_KE4sm_E,
		K4opPTe2z:
			(ref1 = color !== null && color !== void 0 ? color : props.K4opPTe2z) !==
				null && ref1 !== void 0
				? ref1
				: "var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
		tt8lvbGGf:
			(ref2 = title !== null && title !== void 0 ? title : props.tt8lvbGGf) !==
				null && ref2 !== void 0
				? ref2
				: "About",
		TxMQyqfTi: tap !== null && tap !== void 0 ? tap : props.TxMQyqfTi,
		variant:
			(ref3 =
				(_variant = humanReadableVariantMap[props.variant]) !== null &&
				_variant !== void 0
					? _variant
					: props.variant) !== null && ref3 !== void 0
				? ref3
				: "aGHAagPp0",
		x41Bgd582: link !== null && link !== void 0 ? link : props.x41Bgd582,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		tt8lvbGGf,
		x41Bgd582,
		TxMQyqfTi,
		j_KE4sm_E,
		EARkE2sZA,
		K4opPTe2z,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "aGHAagPp0",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapbzpbin = activeVariantCallback(async (...args) => {
		if (TxMQyqfTi) {
			const res = await TxMQyqfTi(...args);
			if (res === false) return false;
		}
	});
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-N0gvu", className, classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<Link href={x41Bgd582} openInNewTab={false}>
						<motion.a
							{...restProps}
							className={`${cx("framer-14fg6c9", className2)} framer-1yxczba`}
							data-framer-name={"Variant 1"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"aGHAagPp0"}
							onTap={onTapbzpbin}
							ref={ref}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"aGHAagPp0-hover": {
										"data-framer-name": void 0,
									},
									"oFZUur6Pc-hover": {
										"data-framer-name": void 0,
									},
									oFZUur6Pc: {
										"data-framer-name": "Menu - Mega",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-18p2dgf"}
								data-framer-name={"About"}
								layoutDependency={layoutDependency}
								layoutId={"IM2nzattM"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-K4opPTe2z-pmUQ8lmqr)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-K4opPTe2z-pmUQ8lmqr": K4opPTe2z,
								}}
								text={tt8lvbGGf}
								variants={{
									"aGHAagPp0-hover": {
										"--extracted-r6o4lv":
											"var(--token-fa32cdec-0e8e-4592-a681-3a125ad70e8e, rgb(228, 168, 83))",
									},
									"oFZUur6Pc-hover": {
										"--extracted-r6o4lv":
											"var(--token-d8aebec7-127a-45a9-b7a0-7e4b0ca8d5d3, rgb(85, 98, 101))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1xcewdd"}
										data-styles-preset={"tYZhcMX2H"}
										style={{
											"--framer-text-color": "var(--extracted-r6o4lv)",
										}}
									>
										{"About"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{j_KE4sm_E && (
								<motion.div
									className={"framer-1ksugyg-container"}
									layoutDependency={layoutDependency}
									layoutId={"AOZik27Mw-container"}
									style={{
										rotate: 90,
									}}
									variants={{
										"aGHAagPp0-hover": {
											rotate: -90,
										},
										"oFZUur6Pc-hover": {
											rotate: -90,
										},
									}}
								>
									<Icon
										color={EARkE2sZA}
										height={"100%"}
										iconSearch={"Home"}
										iconSelection={"ChevronRight"}
										iconStyle15={"Filled"}
										iconStyle2={"Filled"}
										iconStyle7={"Filled"}
										id={"AOZik27Mw"}
										layoutId={"AOZik27Mw"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
										{...addPropertyOverrides(
											{
												"oFZUur6Pc-hover": {
													color:
														'var(--token-fa80fbd3-80c5-4287-9ab3-b2eb46c5a42a, rgb(102, 55, 237)) /* {"name":"Primary"} */',
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							)}
						</motion.a>
					</Link>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-N0gvu [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-N0gvu .framer-1yxczba { display: block; }",
	".framer-N0gvu .framer-14fg6c9 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-N0gvu .framer-18p2dgf { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-N0gvu .framer-1ksugyg-container { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-N0gvu .framer-v-14fg6c9 .framer-14fg6c9, .framer-N0gvu .framer-v-1ug7wbl .framer-14fg6c9 { cursor: pointer; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-N0gvu .framer-14fg6c9 { gap: 0px; } .framer-N0gvu .framer-14fg6c9 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-N0gvu .framer-14fg6c9 > :first-child { margin-left: 0px; } .framer-N0gvu .framer-14fg6c9 > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerpmUQ8lmqr = withCSS(Component, css2, "framer-N0gvu");
var stdin_default = FramerpmUQ8lmqr;
FramerpmUQ8lmqr.displayName = "Menu Item";
FramerpmUQ8lmqr.defaultProps = {
	height: 24,
	width: 42,
};
addPropertyControls(FramerpmUQ8lmqr, {
	variant: {
		options: ["aGHAagPp0", "oFZUur6Pc"],
		optionTitles: ["Variant 1", "Menu - Mega"],
		title: "Variant",
		type: ControlType.Enum,
	},
	tt8lvbGGf: {
		defaultValue: "About",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	x41Bgd582: {
		title: "Link",
		type: ControlType.Link,
	},
	TxMQyqfTi: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
	j_KE4sm_E: {
		defaultValue: false,
		title: "Arrow",
		type: ControlType.Boolean,
	},
	EARkE2sZA: {
		defaultValue:
			'var(--token-1f2d55b1-7509-480d-9086-134655dcd9c7, rgb(17, 17, 17)) /* {"name":"Neutral / 07"} */',
		title: "Arrow Color",
		type: ControlType.Color,
	},
	K4opPTe2z: {
		defaultValue:
			"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
		title: "Color ",
		type: ControlType.Color,
	},
});
addFonts(FramerpmUQ8lmqr, [...MaterialFonts, ...fonts]);

// /:https://framerusercontent.com/modules/uFKJgyipEBxFt5UllyiV/BoDOJwURuaCQbMwXA9Vz/nrNEBm02s.js
var MenuItemFonts = getFonts2(stdin_default);
var cycleOrder2 = ["NAY3vPvDo", "PZnZf2t8R"];
var variantClassNames2 = {
	NAY3vPvDo: "framer-v-1pw3flg",
	PZnZf2t8R: "framer-v-19frut5",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions2 = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap2 = {
	"Variant 1": "NAY3vPvDo",
	"Variant 2": "PZnZf2t8R",
};
var getProps2 = ({ height, id, mouseEnter, mouseLeave, width, ...props }) => {
	var _variant, ref;
	return {
		...props,
		QNm7D3Fet:
			mouseEnter !== null && mouseEnter !== void 0
				? mouseEnter
				: props.QNm7D3Fet,
		ufH3u2QMQ:
			mouseLeave !== null && mouseLeave !== void 0
				? mouseLeave
				: props.ufH3u2QMQ,
		variant:
			(ref =
				(_variant = humanReadableVariantMap2[props.variant]) !== null &&
				_variant !== void 0
					? _variant
					: props.variant) !== null && ref !== void 0
				? ref
				: "NAY3vPvDo",
	};
};
var createLayoutDependency2 = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		QNm7D3Fet,
		ufH3u2QMQ,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "NAY3vPvDo",
		transitions: transitions2,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onMouseEnter1wsdcvd = activeVariantCallback(async (...args) => {
		if (QNm7D3Fet) {
			const res = await QNm7D3Fet(...args);
			if (res === false) return false;
		}
	});
	const onMouseLeavea71tlm = activeVariantCallback(async (...args) => {
		if (ufH3u2QMQ) {
			const res = await ufH3u2QMQ(...args);
			if (res === false) return false;
		}
	});
	const router = useRouter();
	const defaultLayoutId = React2.useId();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion2.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx2("framer-TnWqR", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition2 value={transition}>
					<motion2.div
						{...restProps}
						className={cx2("framer-1pw3flg", className2)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"NAY3vPvDo"}
						onMouseEnter={onMouseEnter1wsdcvd}
						onMouseLeave={onMouseLeavea71tlm}
						ref={ref}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								PZnZf2t8R: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1v9ok8q"}
							data-framer-name={"Mega Menu"}
							layoutDependency={layoutDependency}
							layoutId={"uITfrcjHJ"}
							style={{
								backgroundColor:
									"var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83))",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								boxShadow: "0px 0px 12px 0px rgba(21, 29, 22, 0.12)",
							}}
							variants={{
								PZnZf2t8R: {
									backgroundColor:
										"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
								},
							}}
						>
							<motion2.div
								className={"framer-k85l7a"}
								data-framer-name={"Mega Menu Inner"}
								layoutDependency={layoutDependency}
								layoutId={"sT5gTspwR"}
							>
								<motion2.div
									className={"framer-14ss07a"}
									data-framer-name={"Menu Block"}
									layoutDependency={layoutDependency}
									layoutId={"gkFAvUnsb"}
								>
									<motion2.div
										className={"framer-1o3jc3c"}
										data-framer-name={"Single Menu"}
										layoutDependency={layoutDependency}
										layoutId={"mSNy71dVI"}
									>
										<motion2.div
											className={"framer-5ce27z"}
											data-framer-name={"Singe Menu Inner"}
											layoutDependency={layoutDependency}
											layoutId={"hqHz72plk"}
										>
											<motion2.div
												className={"framer-1hw2f50-container"}
												layoutDependency={layoutDependency}
												layoutId={"nLxg1U4ue-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "nLxg1U4ue",
													layoutId: "nLxg1U4ue",
													link: resolveLink(
														{
															webPageId: "augiA20Il",
														},
														router,
													),
													title: "Homepage",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-1tn9a7g-container"}
												layoutDependency={layoutDependency}
												layoutId={"Bweyt1DGF-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "Bweyt1DGF",
													layoutId: "Bweyt1DGF",
													link: resolveLink(
														{
															webPageId: "js50T9wbk",
														},
														router,
													),
													title: "About Us",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-1axpwvm-container"}
												layoutDependency={layoutDependency}
												layoutId={"d8omOpRrx-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "d8omOpRrx",
													layoutId: "d8omOpRrx",
													link: resolveLink(
														{
															webPageId: "uSQp1V1Rr",
														},
														router,
													),
													title: "Rooms",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-52l4hz-container"}
												layoutDependency={layoutDependency}
												layoutId={"U1QxT9dyQ-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(1, 48, 58)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "U1QxT9dyQ",
													layoutId: "U1QxT9dyQ",
													link: resolveLink(
														{
															webPageId: "WqHBcr8SQ",
														},
														router,
													),
													title: "Pricing",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-15um6nk-container"}
												layoutDependency={layoutDependency}
												layoutId={"N6m0TLDGN-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(1, 48, 58)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "N6m0TLDGN",
													layoutId: "N6m0TLDGN",
													link: resolveLink(
														{
															webPageId: "qo8pkRvhW",
														},
														router,
													),
													title: "Service",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-ao1el7-container"}
												layoutDependency={layoutDependency}
												layoutId={"p_09lfCh_-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "p_09lfCh_",
													layoutId: "p_09lfCh_",
													link: resolveLink(
														{
															webPageId: "VUS3z6n5h",
														},
														router,
													),
													title: "Gallery",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-svick2-container"}
												layoutDependency={layoutDependency}
												layoutId={"n9fR4nPy_-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "n9fR4nPy_",
													layoutId: "n9fR4nPy_",
													link: resolveLink(
														{
															webPageId: "UZLL76nW9",
														},
														router,
													),
													title: "Facilities",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-1x6nu5g-container"}
												layoutDependency={layoutDependency}
												layoutId={"EBeUz0Bu5-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "EBeUz0Bu5",
													layoutId: "EBeUz0Bu5",
													link: resolveLink(
														{
															webPageId: "GZxH1Y62Q",
														},
														router,
													),
													title: "Contact",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
											<motion2.div
												className={"framer-xoootu-container"}
												layoutDependency={layoutDependency}
												layoutId={"RIDUaJ44W-container"}
											>
												{_jsx2(stdin_default, {
													arrow: false,
													arrowColor:
														'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
													color:
														'var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)) /* {"name":"Neutral / 01"} */',
													height: "100%",
													id: "RIDUaJ44W",
													layoutId: "RIDUaJ44W",
													link: resolveLink(
														{
															webPageId: "s6Y_D4pqr",
														},
														router,
													),
													title: "404",
													variant: "aGHAagPp0",
													width: "100%",
													...addPropertyOverrides2(
														{
															PZnZf2t8R: {
																color:
																	'var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) /* {"name":"Neutral / 07"} */',
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</motion2.div>
										</motion2.div>
									</motion2.div>
								</motion2.div>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</motion2.div>
		</LayoutGroup2>
	);
});
var css3 = [
	'.framer-TnWqR [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TnWqR .framer-1k0qpm9 { display: block; }",
	".framer-TnWqR .framer-1pw3flg { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 20px 0px 20px 0px; position: relative; width: min-content; }",
	".framer-TnWqR .framer-1v9ok8q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; min-width: 210px; overflow: hidden; padding: 16px 10px 16px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: 10; }",
	".framer-TnWqR .framer-k85l7a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-TnWqR .framer-14ss07a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-TnWqR .framer-1o3jc3c { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-TnWqR .framer-5ce27z { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-TnWqR .framer-1hw2f50-container, .framer-TnWqR .framer-1tn9a7g-container, .framer-TnWqR .framer-1axpwvm-container, .framer-TnWqR .framer-52l4hz-container, .framer-TnWqR .framer-15um6nk-container, .framer-TnWqR .framer-ao1el7-container, .framer-TnWqR .framer-svick2-container, .framer-TnWqR .framer-1x6nu5g-container, .framer-TnWqR .framer-xoootu-container { flex: none; height: auto; position: relative; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TnWqR .framer-1pw3flg, .framer-TnWqR .framer-1v9ok8q, .framer-TnWqR .framer-k85l7a, .framer-TnWqR .framer-14ss07a, .framer-TnWqR .framer-1o3jc3c, .framer-TnWqR .framer-5ce27z { gap: 0px; } .framer-TnWqR .framer-1pw3flg > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-TnWqR .framer-1pw3flg > :first-child, .framer-TnWqR .framer-1v9ok8q > :first-child, .framer-TnWqR .framer-k85l7a > :first-child, .framer-TnWqR .framer-14ss07a > :first-child { margin-left: 0px; } .framer-TnWqR .framer-1pw3flg > :last-child, .framer-TnWqR .framer-1v9ok8q > :last-child, .framer-TnWqR .framer-k85l7a > :last-child, .framer-TnWqR .framer-14ss07a > :last-child { margin-right: 0px; } .framer-TnWqR .framer-1v9ok8q > * { margin: 0px; margin-left: calc(14px / 2); margin-right: calc(14px / 2); } .framer-TnWqR .framer-k85l7a > *, .framer-TnWqR .framer-14ss07a > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-TnWqR .framer-1o3jc3c > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-TnWqR .framer-1o3jc3c > :first-child, .framer-TnWqR .framer-5ce27z > :first-child { margin-top: 0px; } .framer-TnWqR .framer-1o3jc3c > :last-child, .framer-TnWqR .framer-5ce27z > :last-child { margin-bottom: 0px; } .framer-TnWqR .framer-5ce27z > * { margin: 0px; margin-bottom: calc(18px / 2); margin-top: calc(18px / 2); } }",
	".framer-TnWqR.framer-v-19frut5 .framer-1pw3flg { padding: 30px 0px 20px 0px; }",
];
var FramernrNEBm02s = withCSS2(Component2, css3, "framer-TnWqR");
var stdin_default2 = FramernrNEBm02s;
FramernrNEBm02s.displayName = "Mega Menu";
FramernrNEBm02s.defaultProps = {
	height: 432,
	width: 210,
};
addPropertyControls2(FramernrNEBm02s, {
	variant: {
		options: ["NAY3vPvDo", "PZnZf2t8R"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	QNm7D3Fet: {
		title: "Mouse Enter",
		type: ControlType2.EventHandler,
	},
	ufH3u2QMQ: {
		title: "Mouse Leave",
		type: ControlType2.EventHandler,
	},
});
addFonts2(FramernrNEBm02s, [...MenuItemFonts]);

// virtual:mega-menu
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MegaMenuFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var mega_menu_default = ComponentWithRoot;
export { mega_menu_default as default };
