// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Menu - Mega' // Variant
 * title?: string // Title
 * link?: string // Link
 * tap?: Function // Tap
 * arrow?: boolean // Arrow
 * arrowColor?: string // Arrow Color
 * color ?: string // Color 
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-UQLTEEAL.js";
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:menu-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zlaNb56D7jc8MsRzUuQT/lIZgd8zvsKyfr3eaUA7F/pmUQ8lmqr.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	Link,
	RichText,
	useActiveVariantCallback,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MaterialFonts = getFonts(Icon);
var enabledGestures = {
	aGHAagPp0: {
		hover: true,
	},
	oFZUur6Pc: {
		hover: true,
	},
};
var cycleOrder = ["aGHAagPp0", "oFZUur6Pc"];
var variantClassNames = {
	aGHAagPp0: "framer-v-14fg6c9",
	oFZUur6Pc: "framer-v-1ug7wbl",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1.2,
		stiffness: 300,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Menu - Mega": "oFZUur6Pc",
	"Variant 1": "aGHAagPp0",
};
var getProps = ({
	arrow,
	arrowColor,
	color,
	height,
	id,
	link,
	tap,
	title,
	width,
	...props
}) => {
	var ref, ref1, ref2, _variant, ref3;
	return {
		...props,
		EARkE2sZA:
			(ref =
				arrowColor !== null && arrowColor !== void 0
					? arrowColor
					: props.EARkE2sZA) !== null && ref !== void 0
				? ref
				: 'var(--token-1f2d55b1-7509-480d-9086-134655dcd9c7, rgb(17, 17, 17)) /* {"name":"Neutral / 07"} */',
		j_KE4sm_E: arrow !== null && arrow !== void 0 ? arrow : props.j_KE4sm_E,
		K4opPTe2z:
			(ref1 = color !== null && color !== void 0 ? color : props.K4opPTe2z) !==
				null && ref1 !== void 0
				? ref1
				: "var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
		tt8lvbGGf:
			(ref2 = title !== null && title !== void 0 ? title : props.tt8lvbGGf) !==
				null && ref2 !== void 0
				? ref2
				: "About",
		TxMQyqfTi: tap !== null && tap !== void 0 ? tap : props.TxMQyqfTi,
		variant:
			(ref3 =
				(_variant = humanReadableVariantMap[props.variant]) !== null &&
				_variant !== void 0
					? _variant
					: props.variant) !== null && ref3 !== void 0
				? ref3
				: "aGHAagPp0",
		x41Bgd582: link !== null && link !== void 0 ? link : props.x41Bgd582,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		tt8lvbGGf,
		x41Bgd582,
		TxMQyqfTi,
		j_KE4sm_E,
		EARkE2sZA,
		K4opPTe2z,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "aGHAagPp0",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapbzpbin = activeVariantCallback(async (...args) => {
		if (TxMQyqfTi) {
			const res = await TxMQyqfTi(...args);
			if (res === false) return false;
		}
	});
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-N0gvu", className, classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<Link href={x41Bgd582} openInNewTab={false}>
						<motion.a
							{...restProps}
							className={`${cx("framer-14fg6c9", className2)} framer-1yxczba`}
							data-framer-name={"Variant 1"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"aGHAagPp0"}
							onTap={onTapbzpbin}
							ref={ref}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"aGHAagPp0-hover": {
										"data-framer-name": void 0,
									},
									"oFZUur6Pc-hover": {
										"data-framer-name": void 0,
									},
									oFZUur6Pc: {
										"data-framer-name": "Menu - Mega",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-18p2dgf"}
								data-framer-name={"About"}
								layoutDependency={layoutDependency}
								layoutId={"IM2nzattM"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-K4opPTe2z-pmUQ8lmqr)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-K4opPTe2z-pmUQ8lmqr": K4opPTe2z,
								}}
								text={tt8lvbGGf}
								variants={{
									"aGHAagPp0-hover": {
										"--extracted-r6o4lv":
											"var(--token-fa32cdec-0e8e-4592-a681-3a125ad70e8e, rgb(228, 168, 83))",
									},
									"oFZUur6Pc-hover": {
										"--extracted-r6o4lv":
											"var(--token-d8aebec7-127a-45a9-b7a0-7e4b0ca8d5d3, rgb(85, 98, 101))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1xcewdd"}
										data-styles-preset={"tYZhcMX2H"}
										style={{
											"--framer-text-color": "var(--extracted-r6o4lv)",
										}}
									>
										{"About"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{j_KE4sm_E && (
								<motion.div
									className={"framer-1ksugyg-container"}
									layoutDependency={layoutDependency}
									layoutId={"AOZik27Mw-container"}
									style={{
										rotate: 90,
									}}
									variants={{
										"aGHAagPp0-hover": {
											rotate: -90,
										},
										"oFZUur6Pc-hover": {
											rotate: -90,
										},
									}}
								>
									<Icon
										color={EARkE2sZA}
										height={"100%"}
										iconSearch={"Home"}
										iconSelection={"ChevronRight"}
										iconStyle15={"Filled"}
										iconStyle2={"Filled"}
										iconStyle7={"Filled"}
										id={"AOZik27Mw"}
										layoutId={"AOZik27Mw"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
										{...addPropertyOverrides(
											{
												"oFZUur6Pc-hover": {
													color:
														'var(--token-fa80fbd3-80c5-4287-9ab3-b2eb46c5a42a, rgb(102, 55, 237)) /* {"name":"Primary"} */',
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							)}
						</motion.a>
					</Link>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-N0gvu [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-N0gvu .framer-1yxczba { display: block; }",
	".framer-N0gvu .framer-14fg6c9 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-N0gvu .framer-18p2dgf { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-N0gvu .framer-1ksugyg-container { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-N0gvu .framer-v-14fg6c9 .framer-14fg6c9, .framer-N0gvu .framer-v-1ug7wbl .framer-14fg6c9 { cursor: pointer; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-N0gvu .framer-14fg6c9 { gap: 0px; } .framer-N0gvu .framer-14fg6c9 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-N0gvu .framer-14fg6c9 > :first-child { margin-left: 0px; } .framer-N0gvu .framer-14fg6c9 > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerpmUQ8lmqr = withCSS(Component, css2, "framer-N0gvu");
var stdin_default = FramerpmUQ8lmqr;
FramerpmUQ8lmqr.displayName = "Menu Item";
FramerpmUQ8lmqr.defaultProps = {
	height: 24,
	width: 42,
};
addPropertyControls(FramerpmUQ8lmqr, {
	variant: {
		options: ["aGHAagPp0", "oFZUur6Pc"],
		optionTitles: ["Variant 1", "Menu - Mega"],
		title: "Variant",
		type: ControlType.Enum,
	},
	tt8lvbGGf: {
		defaultValue: "About",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	x41Bgd582: {
		title: "Link",
		type: ControlType.Link,
	},
	TxMQyqfTi: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
	j_KE4sm_E: {
		defaultValue: false,
		title: "Arrow",
		type: ControlType.Boolean,
	},
	EARkE2sZA: {
		defaultValue:
			'var(--token-1f2d55b1-7509-480d-9086-134655dcd9c7, rgb(17, 17, 17)) /* {"name":"Neutral / 07"} */',
		title: "Arrow Color",
		type: ControlType.Color,
	},
	K4opPTe2z: {
		defaultValue:
			"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
		title: "Color ",
		type: ControlType.Color,
	},
});
addFonts(FramerpmUQ8lmqr, [...MaterialFonts, ...fonts]);

// virtual:menu-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "aGHAagPp0",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MenuItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var menu_item_default = ComponentWithRoot;
export { menu_item_default as default };
