// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:play
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mHq3EMyg0G866lz0vy6b/ncLzPqsPNLaoyT9RkAOY/MN0gsIZKz.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getFonts,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MaterialFonts = getFonts(Icon);
var cycleOrder = ["YAlavVK1M"];
var variantClassNames = {
	YAlavVK1M: "framer-v-b7bqus",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var transformTemplate = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YAlavVK1M",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-SpoPy", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-b7bqus", className)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"YAlavVK1M"}
						ref={ref}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-7a1zlm"}
							data-border={true}
							layoutDependency={layoutDependency}
							layoutId={"lidSpCjfh"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									'var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214)) /* {"name":"Neutral / 03"} */',
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 500,
								borderBottomRightRadius: 500,
								borderTopLeftRadius: 500,
								borderTopRightRadius: 500,
							}}
						>
							<motion.div
								className={"framer-1stfh5j-container"}
								layoutDependency={layoutDependency}
								layoutId={"CR5rBOSbu-container"}
								transformTemplate={transformTemplate}
							>
								<Icon
									color={
										'var(--token-f512b2c0-ccff-4c1c-81ef-5b1a68ff0d48, rgb(170, 132, 83)) /* {"name":"Primary"} */'
									}
									height={"100%"}
									iconSearch={"Home"}
									iconSelection={"PlayArrow"}
									iconStyle15={"Filled"}
									iconStyle2={"Filled"}
									iconStyle7={"Filled"}
									id={"CR5rBOSbu"}
									layoutId={"CR5rBOSbu"}
									mirrored={false}
									selectByList={true}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-SpoPy [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SpoPy .framer-1m79yzs { display: block; }",
	".framer-SpoPy .framer-b7bqus { height: 60px; overflow: hidden; position: relative; width: 60px; }",
	".framer-SpoPy .framer-7a1zlm { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 60px); left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-SpoPy .framer-1stfh5j-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); left: 50%; position: absolute; top: 50%; width: 20px; }",
];
var FramerMN0gsIZKz = withCSS(Component, css, "framer-SpoPy");
var stdin_default = FramerMN0gsIZKz;
FramerMN0gsIZKz.displayName = "play";
FramerMN0gsIZKz.defaultProps = {
	height: 60,
	width: 60,
};
addFonts(FramerMN0gsIZKz, [...MaterialFonts]);

// virtual:play
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PlayFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var play_default = ComponentWithRoot;
export { play_default as default };
