// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Variant 2' | 'Variant 3' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-WXRG7P7E.js";
import { className, css, fonts } from "./chunks/chunk-DQ7NIFUT.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-SLRSS6VR.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:pricing-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bqfAIJkFsThjlqzE0bOA/vlDi5gCEcjSQlcQ1FfKF/HX8f3unwu.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	Image,
	RichText as RichText2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/LwWKLnZqCtRkvLDhvLk8/J4eLVaIUL0Sy9utsYVEd/f9z7v91ro.js
import { fontStore } from "unframer";
fontStore.loadWebFontsFromSelectors(["GF;Playfair Display-500"]);
var fonts4 = [
	{
		family: "Playfair Display",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/f9z7v91ro:default",
			url: "https://fonts.gstatic.com/s/playfairdisplay/v36/nuFvD-vYSZviVYUb_rj3ij__anPXJzDwcbmjWBN2PKd3vUDQZNLo_U2r.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/playfairdisplay/v36/nuFvD-vYSZviVYUb_rj3ij__anPXJzDwcbmjWBN2PKd3vUDQZNLo_U2r.ttf",
		weight: "500",
	},
];
var css4 = [
	'.framer-XAdu8 .framer-styles-preset-1pkgc8z:not(.rich-text-wrapper), .framer-XAdu8 .framer-styles-preset-1pkgc8z.rich-text-wrapper h4 { --framer-font-family: "Playfair Display", serif; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.015625em; --framer-line-height: 130%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 810px) { .framer-XAdu8 .framer-styles-preset-1pkgc8z:not(.rich-text-wrapper), .framer-XAdu8 .framer-styles-preset-1pkgc8z.rich-text-wrapper h4 { --framer-font-family: "Playfair Display", serif; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.015625em; --framer-line-height: 130%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-XAdu8 .framer-styles-preset-1pkgc8z:not(.rich-text-wrapper), .framer-XAdu8 .framer-styles-preset-1pkgc8z.rich-text-wrapper h4 { --framer-font-family: "Playfair Display", serif; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.015625em; --framer-line-height: 130%; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className4 = "framer-XAdu8";

// /:https://framerusercontent.com/modules/CHRIjmgmvNt3dclocCCN/mouiG8pkRSacHaO42rDU/DU2ZYH067.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	SVG,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["YjSo1L4qr"];
var variantClassNames = {
	YjSo1L4qr: "framer-v-n7gzji",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var equals = (a, b) => {
	return typeof a === "string" && typeof b === "string"
		? a.toLowerCase() === b.toLowerCase()
		: a === b;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, option, text, width, ...props }) => {
	var ref, ref1;
	return {
		...props,
		d7MaQAWMx:
			(ref = text !== null && text !== void 0 ? text : props.d7MaQAWMx) !==
				null && ref !== void 0
				? ref
				: "Spa & Massage Retreat Special Package",
		Z8kKIczPz:
			(ref1 =
				option !== null && option !== void 0 ? option : props.Z8kKIczPz) !==
				null && ref1 !== void 0
				? ref1
				: "xlPSn6bvF",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		d7MaQAWMx,
		Z8kKIczPz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YjSo1L4qr",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-KaZSI", className, classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-n7gzji", className5)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"YjSo1L4qr"}
						ref={ref}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-yav1b8"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"xBq_q_Bmq"}
						>
							{equals(Z8kKIczPz, "L8_tycEx6") && (
								<SVG
									className={"framer-1151wq1"}
									data-framer-name={"Icon Cross"}
									fill={"rgba(0,0,0,1)"}
									intrinsicHeight={12}
									intrinsicWidth={12}
									layoutDependency={layoutDependency}
									layoutId={"cZEUm9X8y"}
									svg={
										'<svg width="12" height="12" viewBox="-1 -1 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M0.43451 0.434266C0.746929 0.121846 1.25346 0.121846 1.56588 0.434266L5.0002 3.86858L8.43451 0.434266C8.74693 0.121846 9.25346 0.121846 9.56588 0.434266C9.8783 0.746685 9.8783 1.25322 9.56588 1.56564L6.13157 4.99995L9.56588 8.43427C9.8783 8.74669 9.8783 9.25322 9.56588 9.56564C9.25346 9.87806 8.74693 9.87806 8.43451 9.56564L5.0002 6.13132L1.56588 9.56564C1.25346 9.87806 0.746929 9.87806 0.43451 9.56564C0.12209 9.25322 0.12209 8.74669 0.43451 8.43427L3.86882 4.99995L0.43451 1.56564C0.12209 1.25322 0.12209 0.746685 0.43451 0.434266Z" fill="#DDD9D6"/>\n</svg>\n'
									}
									withExternalLayout={true}
								/>
							)}
							{equals(Z8kKIczPz, "xlPSn6bvF") && (
								<SVG
									className={"framer-fcx64p"}
									data-framer-name={"Icon Check"}
									fill={"rgba(0,0,0,1)"}
									intrinsicHeight={10}
									intrinsicWidth={12}
									layoutDependency={layoutDependency}
									layoutId={"I7989:280;102:171"}
									svg={
										'<svg width="12" height="10" viewBox="-1 -1 12 10" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M0.333008 4.66675L2.99967 7.33341L9.66634 0.666748" stroke="#E4A853" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
									}
									withExternalLayout={true}
								/>
							)}
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1rciis2"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"qUozOwA7Z"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)) ",
								"--framer-paragraph-spacing": "0px",
							}}
							text={d7MaQAWMx}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1sb8f1f"}
									data-styles-preset={"Clb2Z6A0U"}
									style={{
										"--framer-text-color": "var(--extracted-r6o4lv)",
									}}
								>
									{"Spa & Massage Retreat Special Package"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css5 = [
	'.framer-KaZSI [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KaZSI .framer-1q603ya { display: block; }",
	".framer-KaZSI .framer-n7gzji { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 301px; }",
	".framer-KaZSI .framer-yav1b8 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); overflow: hidden; position: relative; width: 16px; }",
	".framer-KaZSI .framer-1151wq1 { aspect-ratio: 1 / 1; bottom: 4px; flex: none; left: 2px; position: absolute; top: 2px; width: var(--framer-aspect-ratio-supported, 10px); }",
	".framer-KaZSI .framer-fcx64p { aspect-ratio: 1.2857142857142858 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 7px); left: 2px; position: absolute; right: 5px; top: 3px; }",
	".framer-KaZSI .framer-1rciis2 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-KaZSI .framer-n7gzji { gap: 0px; } .framer-KaZSI .framer-n7gzji > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-KaZSI .framer-n7gzji > :first-child { margin-left: 0px; } .framer-KaZSI .framer-n7gzji > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerDU2ZYH067 = withCSS(Component, css5, "framer-KaZSI");
var stdin_default = FramerDU2ZYH067;
FramerDU2ZYH067.displayName = "Pricing Card List Item";
FramerDU2ZYH067.defaultProps = {
	height: 24,
	width: 301,
};
addPropertyControls(FramerDU2ZYH067, {
	d7MaQAWMx: {
		defaultValue: "Spa & Massage Retreat Special Package",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	Z8kKIczPz: {
		defaultValue: "xlPSn6bvF",
		options: ["xlPSn6bvF", "L8_tycEx6"],
		optionTitles: ["Icon Check", "Icon Cross"],
		title: "Option",
		type: ControlType.Enum,
	},
});
addFonts(FramerDU2ZYH067, [...fonts]);

// /:https://framerusercontent.com/modules/bqfAIJkFsThjlqzE0bOA/vlDi5gCEcjSQlcQ1FfKF/HX8f3unwu.js
var PricingCardListItemFonts = getFonts(stdin_default);
var cycleOrder2 = ["ds6z1V_yr", "S3kbePYB0", "gpHRTKr9P"];
var variantClassNames2 = {
	ds6z1V_yr: "framer-v-9mxmmg",
	gpHRTKr9P: "framer-v-1k29s89",
	S3kbePYB0: "framer-v-msuxs",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions2 = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 2": "S3kbePYB0",
	"Variant 3": "gpHRTKr9P",
	Default: "ds6z1V_yr",
};
var getProps2 = ({ height, id, image, width, ...props }) => {
	var ref, _variant, ref1;
	return {
		...props,
		sxS0Nk1Rj:
			(ref = image !== null && image !== void 0 ? image : props.sxS0Nk1Rj) !==
				null && ref !== void 0
				? ref
				: {
						src: new URL(
							"assets/1024/v6LE3oEvJB3ZjHIsOdO2kKFgkVU.jpg",
							"https://framerusercontent.com/modules/bqfAIJkFsThjlqzE0bOA/vlDi5gCEcjSQlcQ1FfKF/HX8f3unwu.js",
						).href,
						srcSet: `${new URL("assets/512/v6LE3oEvJB3ZjHIsOdO2kKFgkVU.jpg", "https://framerusercontent.com/modules/bqfAIJkFsThjlqzE0bOA/vlDi5gCEcjSQlcQ1FfKF/HX8f3unwu.js").href} 512w, ${new URL("assets/1024/v6LE3oEvJB3ZjHIsOdO2kKFgkVU.jpg", "https://framerusercontent.com/modules/bqfAIJkFsThjlqzE0bOA/vlDi5gCEcjSQlcQ1FfKF/HX8f3unwu.js").href} 1024w, ${new URL("assets/2048/v6LE3oEvJB3ZjHIsOdO2kKFgkVU.jpg", "https://framerusercontent.com/modules/bqfAIJkFsThjlqzE0bOA/vlDi5gCEcjSQlcQ1FfKF/HX8f3unwu.js").href} 2048w, ${new URL("assets/v6LE3oEvJB3ZjHIsOdO2kKFgkVU.jpg", "https://framerusercontent.com/modules/bqfAIJkFsThjlqzE0bOA/vlDi5gCEcjSQlcQ1FfKF/HX8f3unwu.js").href} 4096w`,
					},
		variant:
			(ref1 =
				(_variant = humanReadableVariantMap[props.variant]) !== null &&
				_variant !== void 0
					? _variant
					: props.variant) !== null && ref1 !== void 0
				? ref1
				: "ds6z1V_yr",
	};
};
var createLayoutDependency2 = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		sxS0Nk1Rj,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "ds6z1V_yr",
		transitions: transitions2,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const defaultLayoutId = React2.useId();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion2.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx2(
					"framer-M850z",
					className2,
					className4,
					className3,
					classNames,
				)}
				style={{
					display: "contents",
				}}
			>
				<Transition2 value={transition}>
					<motion2.div
						{...restProps}
						className={cx2("framer-9mxmmg", className5)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"ds6z1V_yr"}
						ref={ref}
						style={{
							backgroundColor:
								"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								gpHRTKr9P: {
									"data-framer-name": "Variant 3",
								},
								S3kbePYB0: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes: "min(416px, 100vw)",
								...toResponsiveImage(sxS0Nk1Rj),
							}}
							className={"framer-1kt2g69"}
							data-framer-name={"Pricing Card Image"}
							layoutDependency={layoutDependency}
							layoutId={"TVO83bmaF"}
						/>
						<motion2.div
							className={"framer-125o4wm"}
							data-framer-name={"Pricing Card Body"}
							layoutDependency={layoutDependency}
							layoutId={"BtMSA_p0z"}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-1vijdok"}
								data-framer-name={"Pricing Card Title"}
								layoutDependency={layoutDependency}
								layoutId={"d41r6D5_h"}
								style={{
									"--extracted-1eung3n":
										"var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)) ",
									"--framer-paragraph-spacing": "0px",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										gpHRTKr9P: {
											children: (
												<React2.Fragment>
													<motion2.h4
														className={"framer-styles-preset-m5v4m7"}
														data-styles-preset={"r8yG0RPK0"}
														style={{
															"--framer-text-color": "var(--extracted-1eung3n)",
														}}
													>
														{"Room Breakfast"}
													</motion2.h4>
												</React2.Fragment>
											),
										},
										S3kbePYB0: {
											children: (
												<React2.Fragment>
													<motion2.h4
														className={"framer-styles-preset-m5v4m7"}
														data-styles-preset={"r8yG0RPK0"}
														style={{
															"--framer-text-color": "var(--extracted-1eung3n)",
														}}
													>
														{"Drinks Included"}
													</motion2.h4>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.h4
										className={"framer-styles-preset-m5v4m7"}
										data-styles-preset={"r8yG0RPK0"}
										style={{
											"--framer-text-color": "var(--extracted-1eung3n)",
										}}
									>
										{"Room Cleaning"}
									</motion2.h4>
								</React2.Fragment>
							</RichText2>
							<motion2.div
								className={"framer-1ixplru"}
								data-framer-name={"Pricing Card Price"}
								layoutDependency={layoutDependency}
								layoutId={"wSkpon2Zr"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-3b157a"}
									data-framer-name={"Pricing Card Price"}
									layoutDependency={layoutDependency}
									layoutId={"ilj95VPDp"}
									style={{
										"--extracted-1eung3n":
											"var(--token-fa32cdec-0e8e-4592-a681-3a125ad70e8e, rgb(228, 168, 83)) ",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											gpHRTKr9P: {
												children: (
													<React2.Fragment>
														<motion2.h4
															className={"framer-styles-preset-1pkgc8z"}
															data-styles-preset={"f9z7v91ro"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1eung3n)",
															}}
														>
															{"$20"}
														</motion2.h4>
													</React2.Fragment>
												),
											},
											S3kbePYB0: {
												children: (
													<React2.Fragment>
														<motion2.h4
															className={"framer-styles-preset-1pkgc8z"}
															data-styles-preset={"f9z7v91ro"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1eung3n)",
															}}
														>
															{"$30"}
														</motion2.h4>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.h4
											className={"framer-styles-preset-1pkgc8z"}
											data-styles-preset={"f9z7v91ro"}
											style={{
												"--framer-text-color": "var(--extracted-1eung3n)",
											}}
										>
											{"$60"}
										</motion2.h4>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-46odch"}
									data-framer-name={"Pricing Card Time"}
									layoutDependency={layoutDependency}
									layoutId={"GorUg6gVW"}
									style={{
										"--extracted-1lwpl3i":
											"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)) ",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											gpHRTKr9P: {
												children: (
													<React2.Fragment>
														<motion2.h5
															className={"framer-styles-preset-111ime3"}
															data-styles-preset={"SbX0d4LkA"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i)",
															}}
														>
															{"/ daily"}
														</motion2.h5>
													</React2.Fragment>
												),
											},
											S3kbePYB0: {
												children: (
													<React2.Fragment>
														<motion2.h5
															className={"framer-styles-preset-111ime3"}
															data-styles-preset={"SbX0d4LkA"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i)",
															}}
														>
															{"/ daily"}
														</motion2.h5>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.h5
											className={"framer-styles-preset-111ime3"}
											data-styles-preset={"SbX0d4LkA"}
											style={{
												"--framer-text-color": "var(--extracted-1lwpl3i)",
											}}
										>
											{"/ month"}
										</motion2.h5>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
							<motion2.div
								className={"framer-1ew1fpb"}
								data-framer-name={"Pricing Card  list"}
								layoutDependency={layoutDependency}
								layoutId={"U7CwrdYw9"}
							>
								<motion2.div
									className={"framer-p8nnhf-container"}
									layoutDependency={layoutDependency}
									layoutId={"zuEJwZp4_-container"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "zuEJwZp4_",
										layoutId: "zuEJwZp4_",
										option: "xlPSn6bvF",
										style: {
											width: "100%",
										},
										text: "Spa & Massage Retreat Special Package",
										width: "100%",
										...addPropertyOverrides(
											{
												gpHRTKr9P: {
													text: "One Time Food",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
								<motion2.div
									className={"framer-1m0fyzk-container"}
									layoutDependency={layoutDependency}
									layoutId={"bipDrySCA-container"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "bipDrySCA",
										layoutId: "bipDrySCA",
										option: "L8_tycEx6",
										style: {
											width: "100%",
										},
										text: "Spa & Massage Retreat Special Package",
										width: "100%",
										...addPropertyOverrides(
											{
												S3kbePYB0: {
													option: "xlPSn6bvF",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
								<motion2.div
									className={"framer-12jmv9i-container"}
									layoutDependency={layoutDependency}
									layoutId={"QsGj_27yk-container"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "QsGj_27yk",
										layoutId: "QsGj_27yk",
										option: "L8_tycEx6",
										style: {
											width: "100%",
										},
										text: "Spa & Massage Retreat Special Package",
										width: "100%",
										...addPropertyOverrides(
											{
												S3kbePYB0: {
													option: "xlPSn6bvF",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</motion2.div>
		</LayoutGroup2>
	);
});
var css6 = [
	'.framer-M850z [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-M850z .framer-1xiqa70 { display: block; }",
	".framer-M850z .framer-9mxmmg { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 416px; }",
	".framer-M850z .framer-1kt2g69 { aspect-ratio: 1.664 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 250px); position: relative; width: 100%; }",
	".framer-M850z .framer-125o4wm { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 40px 30px 40px 30px; position: relative; width: 100%; }",
	".framer-M850z .framer-1vijdok, .framer-M850z .framer-3b157a, .framer-M850z .framer-46odch { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-M850z .framer-1ixplru { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-M850z .framer-1ew1fpb { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-M850z .framer-p8nnhf-container, .framer-M850z .framer-1m0fyzk-container, .framer-M850z .framer-12jmv9i-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-M850z .framer-9mxmmg, .framer-M850z .framer-125o4wm, .framer-M850z .framer-1ixplru, .framer-M850z .framer-1ew1fpb { gap: 0px; } .framer-M850z .framer-9mxmmg > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-M850z .framer-9mxmmg > :first-child, .framer-M850z .framer-125o4wm > :first-child, .framer-M850z .framer-1ew1fpb > :first-child { margin-top: 0px; } .framer-M850z .framer-9mxmmg > :last-child, .framer-M850z .framer-125o4wm > :last-child, .framer-M850z .framer-1ew1fpb > :last-child { margin-bottom: 0px; } .framer-M850z .framer-125o4wm > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-M850z .framer-1ixplru > * { margin: 0px; margin-left: calc(5px / 2); margin-right: calc(5px / 2); } .framer-M850z .framer-1ixplru > :first-child { margin-left: 0px; } .framer-M850z .framer-1ixplru > :last-child { margin-right: 0px; } .framer-M850z .framer-1ew1fpb > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	...css2,
	...css4,
	...css3,
];
var FramerHX8f3unwu = withCSS2(Component2, css6, "framer-M850z");
var stdin_default2 = FramerHX8f3unwu;
FramerHX8f3unwu.displayName = "Pricing Card";
FramerHX8f3unwu.defaultProps = {
	height: 549,
	width: 416,
};
addPropertyControls2(FramerHX8f3unwu, {
	variant: {
		options: ["ds6z1V_yr", "S3kbePYB0", "gpHRTKr9P"],
		optionTitles: ["Default", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	sxS0Nk1Rj: {
		__defaultAssetReference:
			"data:framer/asset-reference,v6LE3oEvJB3ZjHIsOdO2kKFgkVU.jpg?originalFilename=Image.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType2.ResponsiveImage,
	},
});
addFonts2(FramerHX8f3unwu, [
	...PricingCardListItemFonts,
	...fonts2,
	...fonts4,
	...fonts3,
]);

// virtual:pricing-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PricingCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var pricing_card_default = ComponentWithRoot;
export { pricing_card_default as default };
