// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
 * option?: 'Icon Check' | 'Icon Cross' // Option
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-DQ7NIFUT.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:pricing-card-list-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fYXvE4mYfv5cvIAtMqrx/lPRLWnVb2hsOzyPocuIy/DU2ZYH067.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	SVG,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["YjSo1L4qr"];
var variantClassNames = {
	YjSo1L4qr: "framer-v-n7gzji",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var equals = (a, b) => {
	return typeof a === "string" && typeof b === "string"
		? a.toLowerCase() === b.toLowerCase()
		: a === b;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, option, text, width, ...props }) => {
	var ref, ref1;
	return {
		...props,
		d7MaQAWMx:
			(ref = text !== null && text !== void 0 ? text : props.d7MaQAWMx) !==
				null && ref !== void 0
				? ref
				: "Spa & Massage Retreat Special Package",
		Z8kKIczPz:
			(ref1 =
				option !== null && option !== void 0 ? option : props.Z8kKIczPz) !==
				null && ref1 !== void 0
				? ref1
				: "xlPSn6bvF",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		d7MaQAWMx,
		Z8kKIczPz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YjSo1L4qr",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-KaZSI", className, classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-n7gzji", className2)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"YjSo1L4qr"}
						ref={ref}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-yav1b8"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"xBq_q_Bmq"}
						>
							{equals(Z8kKIczPz, "L8_tycEx6") && (
								<SVG
									className={"framer-1151wq1"}
									data-framer-name={"Icon Cross"}
									fill={"rgba(0,0,0,1)"}
									intrinsicHeight={12}
									intrinsicWidth={12}
									layoutDependency={layoutDependency}
									layoutId={"cZEUm9X8y"}
									svg={
										'<svg width="12" height="12" viewBox="-1 -1 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M0.43451 0.434266C0.746929 0.121846 1.25346 0.121846 1.56588 0.434266L5.0002 3.86858L8.43451 0.434266C8.74693 0.121846 9.25346 0.121846 9.56588 0.434266C9.8783 0.746685 9.8783 1.25322 9.56588 1.56564L6.13157 4.99995L9.56588 8.43427C9.8783 8.74669 9.8783 9.25322 9.56588 9.56564C9.25346 9.87806 8.74693 9.87806 8.43451 9.56564L5.0002 6.13132L1.56588 9.56564C1.25346 9.87806 0.746929 9.87806 0.43451 9.56564C0.12209 9.25322 0.12209 8.74669 0.43451 8.43427L3.86882 4.99995L0.43451 1.56564C0.12209 1.25322 0.12209 0.746685 0.43451 0.434266Z" fill="#DDD9D6"/>\n</svg>\n'
									}
									withExternalLayout={true}
								/>
							)}
							{equals(Z8kKIczPz, "xlPSn6bvF") && (
								<SVG
									className={"framer-fcx64p"}
									data-framer-name={"Icon Check"}
									fill={"rgba(0,0,0,1)"}
									intrinsicHeight={10}
									intrinsicWidth={12}
									layoutDependency={layoutDependency}
									layoutId={"I7989:280;102:171"}
									svg={
										'<svg width="12" height="10" viewBox="-1 -1 12 10" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M0.333008 4.66675L2.99967 7.33341L9.66634 0.666748" stroke="#E4A853" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
									}
									withExternalLayout={true}
								/>
							)}
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1rciis2"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"qUozOwA7Z"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)) ",
								"--framer-paragraph-spacing": "0px",
							}}
							text={d7MaQAWMx}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1sb8f1f"}
									data-styles-preset={"Clb2Z6A0U"}
									style={{
										"--framer-text-color": "var(--extracted-r6o4lv)",
									}}
								>
									{"Spa & Massage Retreat Special Package"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-KaZSI [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KaZSI .framer-1q603ya { display: block; }",
	".framer-KaZSI .framer-n7gzji { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 301px; }",
	".framer-KaZSI .framer-yav1b8 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); overflow: hidden; position: relative; width: 16px; }",
	".framer-KaZSI .framer-1151wq1 { aspect-ratio: 1 / 1; bottom: 4px; flex: none; left: 2px; position: absolute; top: 2px; width: var(--framer-aspect-ratio-supported, 10px); }",
	".framer-KaZSI .framer-fcx64p { aspect-ratio: 1.2857142857142858 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 7px); left: 2px; position: absolute; right: 5px; top: 3px; }",
	".framer-KaZSI .framer-1rciis2 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-KaZSI .framer-n7gzji { gap: 0px; } .framer-KaZSI .framer-n7gzji > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-KaZSI .framer-n7gzji > :first-child { margin-left: 0px; } .framer-KaZSI .framer-n7gzji > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerDU2ZYH067 = withCSS(Component, css2, "framer-KaZSI");
var stdin_default = FramerDU2ZYH067;
FramerDU2ZYH067.displayName = "Pricing Card List Item";
FramerDU2ZYH067.defaultProps = {
	height: 24,
	width: 301,
};
addPropertyControls(FramerDU2ZYH067, {
	d7MaQAWMx: {
		defaultValue: "Spa & Massage Retreat Special Package",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	Z8kKIczPz: {
		defaultValue: "xlPSn6bvF",
		options: ["xlPSn6bvF", "L8_tycEx6"],
		optionTitles: ["Icon Check", "Icon Cross"],
		title: "Option",
		type: ControlType.Enum,
	},
});
addFonts(FramerDU2ZYH067, [...fonts]);

// virtual:pricing-card-list-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PricingCardListItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var pricing_card_list_item_default = ComponentWithRoot;
export { pricing_card_list_item_default as default };
