// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Center' | 'Variant 3' // Variant
 * image ?: {src: string, srcSet?: string, alt?: string} // Image 
 * title?: string // Title
 * text?: string // Text
 * link?: string // Link
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-CL76FT5C.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-BCA7MXE7.js";
import { className, css, fonts } from "./chunks/chunk-J7DO4Q5N.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:product-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wx7BjTUbmwADkoncHNpm/0somkPdAVsR7iVnx0CIa/bwyJfcm5k.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["HTutVs6ij", "L3lcwOqa3", "TXoHTBoDV"];
var serializationHash = "framer-1IKRL";
var variantClassNames = {
	HTutVs6ij: "framer-v-anla0h",
	L3lcwOqa3: "framer-v-hndxdf",
	TXoHTBoDV: "framer-v-18smvkp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 3": "TXoHTBoDV",
	Center: "L3lcwOqa3",
	Default: "HTutVs6ij",
};
var getProps = ({ height, id, image, link, text, title, width, ...props }) => {
	return {
		...props,
		DVmQlSvyK: image ??
			props.DVmQlSvyK ?? {
				pixelHeight: 760,
				pixelWidth: 832,
				src: "https://framerusercontent.com/images/3JEmkyfQcKudy7CnshNV7I4idM.png?width=832&height=760",
				srcSet:
					"https://framerusercontent.com/images/3JEmkyfQcKudy7CnshNV7I4idM.png?scale-down-to=512&width=832&height=760 512w,https://framerusercontent.com/images/3JEmkyfQcKudy7CnshNV7I4idM.png?width=832&height=760 832w",
			},
		hWqC6IpdA: title ?? props.hWqC6IpdA ?? "Cozy Room",
		nb08MNnfI: link ?? props.nb08MNnfI,
		stFWEiFIM: text ?? props.stFWEiFIM ?? "Price from $132.0 Night",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "HTutVs6ij",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		DVmQlSvyK: DVmQlSvyK2,
		hWqC6IpdA: hWqC6IpdA2,
		stFWEiFIM: stFWEiFIM2,
		nb08MNnfI: nb08MNnfI2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "HTutVs6ij",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEntermzgb3r = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("TXoHTBoDV");
	});
	const onMouseLeave1xp8wk6 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("HTutVs6ij");
	});
	const sharedStyleClassNames = [className3, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-anla0h",
							className4,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"HTutVs6ij"}
						onMouseEnter={onMouseEntermzgb3r}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								L3lcwOqa3: {
									"data-framer-name": "Center",
								},
								TXoHTBoDV: {
									"data-framer-name": "Variant 3",
									onMouseLeave: onMouseLeave1xp8wk6,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-p4js0"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"bzXYgwrmK"}
						>
							<Link
								href={nb08MNnfI2}
								motionChild={true}
								nodeId={"zBDTtiis7"}
								openInNewTab={false}
								scopeId={"bwyJfcm5k"}
							>
								<Image
									as={"a"}
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 380) - 0 - 380) / 2 +
													0 +
													0) +
												0,
										),
										sizes: componentViewport?.width || "100vw",
										...toResponsiveImage(DVmQlSvyK2),
									}}
									className={"framer-19zo6o0 framer-109zce7"}
									data-framer-name={"Product Card Image"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"zBDTtiis7"}
									{...addPropertyOverrides(
										{
											L3lcwOqa3: {
												"data-highlight": void 0,
												onTap: void 0,
											},
											TXoHTBoDV: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 380) - 0 - 380) /
																2 +
																0 +
																0) +
															-29,
													),
													sizes: `calc(${componentViewport?.width || "100vw"} * 1.1538)`,
													...toResponsiveImage(DVmQlSvyK2),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</Link>
						</motion.div>
						<motion.div
							className={"framer-bb5bu0"}
							data-framer-name={"Product Card Body"}
							layoutDependency={layoutDependency}
							layoutId={"kpovGA29Q"}
						>
							<motion.div
								className={"framer-1p8k2rq"}
								data-framer-name={"Product Card Text Block"}
								layoutDependency={layoutDependency}
								layoutId={"F6_kw_Hr5"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-dl94os"}
									data-framer-name={"Product Card Title"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"e5eKitVDQ"}
									style={{
										"--extracted-1eung3n":
											"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
									}}
									text={hWqC6IpdA2}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											L3lcwOqa3: {
												children: (
													<React.Fragment>
														<motion.h4
															className={"framer-styles-preset-m5v4m7"}
															data-styles-preset={"r8yG0RPK0"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-1eung3n, var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={nb08MNnfI2}
																motionChild={true}
																nodeId={"e5eKitVDQ"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"bwyJfcm5k"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-y5s2qt"}
																	data-styles-preset={"ybRKRcLeC"}
																>
																	{"Cozy Room"}
																</motion.a>
															</Link>
														</motion.h4>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-m5v4m7"}
											data-styles-preset={"r8yG0RPK0"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255)))",
											}}
										>
											<Link
												href={nb08MNnfI2}
												motionChild={true}
												nodeId={"e5eKitVDQ"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"bwyJfcm5k"}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-y5s2qt"}
													data-styles-preset={"ybRKRcLeC"}
												>
													{"Cozy Room"}
												</motion.a>
											</Link>
										</motion.h4>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-g60bht"}
									data-framer-name={"Product Card Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"shOtpbEZe"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214))",
									}}
									text={stFWEiFIM2}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											L3lcwOqa3: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1sb8f1f"}
															data-styles-preset={"Clb2Z6A0U"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214)))",
															}}
														>
															{"Price from $132.0 Night"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1sb8f1f"}
											data-styles-preset={"Clb2Z6A0U"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214)))",
											}}
										>
											{"Price from $132.0 Night"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-1IKRL.framer-109zce7, .framer-1IKRL .framer-109zce7 { display: block; }",
	".framer-1IKRL.framer-anla0h { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 416px; }",
	".framer-1IKRL .framer-p4js0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 380px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-1IKRL .framer-19zo6o0 { cursor: pointer; flex: none; height: 380px; position: relative; text-decoration: none; width: 100%; }",
	".framer-1IKRL .framer-bb5bu0 { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; height: min-content; justify-content: space-between; left: 0px; overflow: visible; padding: 20px 30px 20px 30px; position: absolute; width: 100%; z-index: 1; }",
	".framer-1IKRL .framer-1p8k2rq { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 10px 0px 0px; position: relative; width: 1px; }",
	".framer-1IKRL .framer-dl94os, .framer-1IKRL .framer-g60bht { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-1IKRL.framer-v-hndxdf .framer-19zo6o0 { cursor: unset; }",
	".framer-1IKRL.framer-v-hndxdf .framer-bb5bu0 { flex-direction: column; gap: 12px; justify-content: center; }",
	".framer-1IKRL.framer-v-hndxdf .framer-1p8k2rq { align-content: center; align-items: center; flex: none; justify-content: center; width: 100%; }",
	".framer-1IKRL.framer-v-18smvkp .framer-19zo6o0 { height: 438px; width: 115%; }",
	...css3,
	...css2,
	...css,
];
var FramerbwyJfcm5k = withCSS(Component, css4, "framer-1IKRL");
var stdin_default = FramerbwyJfcm5k;
FramerbwyJfcm5k.displayName = "Product Card";
FramerbwyJfcm5k.defaultProps = {
	height: 380,
	width: 416,
};
addPropertyControls(FramerbwyJfcm5k, {
	variant: {
		options: ["HTutVs6ij", "L3lcwOqa3", "TXoHTBoDV"],
		optionTitles: ["Default", "Center", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	DVmQlSvyK: {
		__defaultAssetReference:
			"data:framer/asset-reference,3JEmkyfQcKudy7CnshNV7I4idM.png?originalFilename=room-image-01.png&preferredSize=auto",
		title: "Image ",
		type: ControlType.ResponsiveImage,
	},
	hWqC6IpdA: {
		defaultValue: "Cozy Room",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	stFWEiFIM: {
		defaultValue: "Price from $132.0 Night",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	nb08MNnfI: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerbwyJfcm5k,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:product-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "L3lcwOqa3",
	xl: "HTutVs6ij",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProductCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var product_card_default = ComponentWithRoot;
export { product_card_default as default };
