// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Variant 2' | 'Phone' | 'Tablet' | 'Variant 2 Tablet' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * subtitle?: string // Subtitle
 * title?: string // Title
 * text?: string // Text
 * link?: string // Link
 * newTab?: boolean // New Tab
}} Props

 */
import {
	className,
	className2,
	css,
	css2,
	fonts,
	fonts2,
} from "./chunks/chunk-A2LYUWB4.js";
import { stdin_default } from "./chunks/chunk-WZBDU7EE.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:service-widget
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tMXAMMxIosWwxm4La5SH/YZ4bNL6uNwDBybnIU5w6/cmakoftLV.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	Image,
	Link,
	RichText,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/pxiKG1BXp6vsZnq76yKY/LYXzWRANjWGDpu2LJdqa/LseYDyRFN.js
import { fontStore } from "unframer";
fontStore.loadWebFontsFromSelectors([]);
var fonts3 = [];
var css3 = [
	'.framer-Q4Aob .framer-styles-preset-sijqht:not(.rich-text-wrapper), .framer-Q4Aob .framer-styles-preset-sijqht.rich-text-wrapper a { --framer-link-current-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b) /* {"name":"Neutral / 07"} */; --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b) /* {"name":"Neutral / 07"} */; --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, #1b1b1b); --framer-link-text-decoration: none; }',
];
var className3 = "framer-Q4Aob";

// /:https://framerusercontent.com/modules/4Iqrd6zpvf4pPVALofhP/ySmXmISEK7gnPthFxZL1/posBLbxeL.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadWebFontsFromSelectors(["GF;Barlow-regular"]);
var fonts4 = [
	{
		family: "Barlow",
		moduleAsset: {
			localModuleIdentifier: "local-module:css/posBLbxeL:default",
			url: "https://fonts.gstatic.com/s/barlow/v12/7cHpv4kjgoGqM7EPC8E46HsxnA.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/barlow/v12/7cHpv4kjgoGqM7EPC8E46HsxnA.ttf",
		weight: "400",
	},
];
var css4 = [
	'.framer-M428l .framer-styles-preset-1wl4agi:not(.rich-text-wrapper), .framer-M428l .framer-styles-preset-1wl4agi.rich-text-wrapper p { --framer-font-family: "Barlow", "Barlow Placeholder", sans-serif; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, #3d3a38); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 991px) and (min-width: 0px) { .framer-M428l .framer-styles-preset-1wl4agi:not(.rich-text-wrapper), .framer-M428l .framer-styles-preset-1wl4agi.rich-text-wrapper p { --framer-font-family: "Barlow", "Barlow Placeholder", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 150%; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, #3d3a38); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className4 = "framer-M428l";

// /:https://framerusercontent.com/modules/tMXAMMxIosWwxm4La5SH/YZ4bNL6uNwDBybnIU5w6/cmakoftLV.js
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = [
	"VwMacgI9x",
	"hzdq50srG",
	"J0h__7E7k",
	"K11kyKdzf",
	"xupnY_m5T",
];
var variantClassNames = {
	hzdq50srG: "framer-v-1hbzd9b",
	J0h__7E7k: "framer-v-1xmif2u",
	K11kyKdzf: "framer-v-12xm5bh",
	VwMacgI9x: "framer-v-14sto0w",
	xupnY_m5T: "framer-v-14ldy7r",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 2 Tablet": "xupnY_m5T",
	"Variant 2": "hzdq50srG",
	Default: "VwMacgI9x",
	Phone: "J0h__7E7k",
	Tablet: "K11kyKdzf",
};
var getProps = ({
	height,
	id,
	image,
	link,
	newTab,
	subtitle,
	text,
	title,
	width,
	...props
}) => {
	return {
		...props,
		buCnMsH9E:
			text ??
			props.buCnMsH9E ??
			"Well-trained restaurant staff collaborate harmoniously to orchestrate these elements, culminating in a memorable and satisfying dining venture.",
		CIgwIieY3: newTab ?? props.CIgwIieY3,
		ibAcBR7vA: title ?? props.ibAcBR7vA ?? "The Restaurant",
		JVofx01uU: link ?? props.JVofx01uU,
		Nk6Fi3exM: subtitle ?? props.Nk6Fi3exM ?? "BEST FOOD",
		oCYyIcKiB: image ??
			props.oCYyIcKiB ?? {
				src: new URL(
					"assets/2048/hZfpzM20KHHp6sze1i5OJ1Jrww.jpg",
					"https://framerusercontent.com/modules/tMXAMMxIosWwxm4La5SH/YZ4bNL6uNwDBybnIU5w6/cmakoftLV.js",
				).href,
				srcSet: `${new URL("assets/512/hZfpzM20KHHp6sze1i5OJ1Jrww.jpg", "https://framerusercontent.com/modules/tMXAMMxIosWwxm4La5SH/YZ4bNL6uNwDBybnIU5w6/cmakoftLV.js").href} 512w, ${new URL("assets/1024/hZfpzM20KHHp6sze1i5OJ1Jrww.jpg", "https://framerusercontent.com/modules/tMXAMMxIosWwxm4La5SH/YZ4bNL6uNwDBybnIU5w6/cmakoftLV.js").href} 1024w, ${new URL("assets/2048/hZfpzM20KHHp6sze1i5OJ1Jrww.jpg", "https://framerusercontent.com/modules/tMXAMMxIosWwxm4La5SH/YZ4bNL6uNwDBybnIU5w6/cmakoftLV.js").href} 2048w, ${new URL("assets/hZfpzM20KHHp6sze1i5OJ1Jrww.jpg", "https://framerusercontent.com/modules/tMXAMMxIosWwxm4La5SH/YZ4bNL6uNwDBybnIU5w6/cmakoftLV.js").href} 3872w`,
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "VwMacgI9x",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		oCYyIcKiB,
		Nk6Fi3exM,
		ibAcBR7vA,
		buCnMsH9E,
		JVofx01uU,
		CIgwIieY3,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "VwMacgI9x",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx(
					"framer-wZtKz",
					className2,
					className,
					className3,
					className4,
					classNames,
				)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-14sto0w", className5)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"VwMacgI9x"}
						ref={ref}
						style={{
							backgroundColor:
								"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								hzdq50srG: {
									"data-framer-name": "Variant 2",
								},
								J0h__7E7k: {
									"data-framer-name": "Phone",
								},
								K11kyKdzf: {
									"data-framer-name": "Tablet",
								},
								xupnY_m5T: {
									"data-framer-name": "Variant 2 Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Link href={JVofx01uU} openInNewTab={false}>
							<Image
								as={"a"}
								background={{
									alt: "",
									fit: "fill",
									sizes: "calc(min(1296px, 100vw) / 2)",
									...toResponsiveImage(oCYyIcKiB),
								}}
								className={"framer-1atp1u3 framer-9n26kc"}
								data-framer-name={"Service Card Image"}
								layoutDependency={layoutDependency}
								layoutId={"qnfo25btP"}
								{...addPropertyOverrides(
									{
										J0h__7E7k: {
											background: {
												alt: "",
												fit: "fill",
												sizes: "min(375px, 100vw)",
												...toResponsiveImage(oCYyIcKiB),
											},
										},
										K11kyKdzf: {
											background: {
												alt: "",
												fit: "fill",
												sizes: "calc(min(768px, 100vw) / 2)",
												...toResponsiveImage(oCYyIcKiB),
											},
										},
										xupnY_m5T: {
											background: {
												alt: "",
												fit: "fill",
												sizes: "calc(min(768px, 100vw) / 2)",
												...toResponsiveImage(oCYyIcKiB),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</Link>
						<motion.div
							className={"framer-vtwhsj"}
							data-framer-name={"Service Card Body"}
							layoutDependency={layoutDependency}
							layoutId={"BLZU4JBbO"}
						>
							<motion.div
								className={"framer-1sh40gd"}
								data-framer-name={"Service Card Text Block"}
								layoutDependency={layoutDependency}
								layoutId={"x3P14Hz7x"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1gx1m1p"}
									data-framer-name={"Subtitle"}
									layoutDependency={layoutDependency}
									layoutId={"R_JDPorq7"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={Nk6Fi3exM}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-x2j49s"}
											data-styles-preset={"jYkXtflJ5"}
										>
											{"BEST FOOD"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ktjtyo"}
									data-framer-name={"Service Card Title"}
									layoutDependency={layoutDependency}
									layoutId={"jRWZNa_ZP"}
									style={{
										"--extracted-1eung3n":
											"var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={ibAcBR7vA}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1pkgc8z"}
											data-styles-preset={"f9z7v91ro"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color": "var(--extracted-1eung3n)",
											}}
										>
											<Link
												href={JVofx01uU}
												openInNewTab={false}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-sijqht"}
													data-styles-preset={"LseYDyRFN"}
												>
													{"The Restaurant"}
												</motion.a>
											</Link>
										</motion.h4>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-kkmvnx"}
									data-framer-name={"Service Card Text"}
									layoutDependency={layoutDependency}
									layoutId={"YysXTGvnB"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)) ",
										"--framer-paragraph-spacing": "0px",
									}}
									text={buCnMsH9E}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1wl4agi"}
											data-styles-preset={"posBLbxeL"}
											style={{
												"--framer-text-color": "var(--extracted-r6o4lv)",
											}}
										>
											{
												"Well-trained restaurant staff collaborate harmoniously to orchestrate these elements, culminating in a memorable and satisfying dining venture."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-upd07g-container"}
								layoutDependency={layoutDependency}
								layoutId={"eXXZl8p_h-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "eXXZl8p_h",
									layoutId: "eXXZl8p_h",
									link: JVofx01uU,
									newTab: CIgwIieY3,
									text: "Learn More",
									variant: "JX9XRUe76",
									width: "100%",
									...addPropertyOverrides(
										{
											J0h__7E7k: {
												variant: "CS2_loij1",
											},
											K11kyKdzf: {
												variant: "CS2_loij1",
											},
											xupnY_m5T: {
												variant: "CS2_loij1",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css5 = [
	'.framer-wZtKz [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wZtKz .framer-9n26kc { display: block; }",
	".framer-wZtKz .framer-14sto0w { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1296px; }",
	".framer-wZtKz .framer-1atp1u3 { aspect-ratio: 1.4179431072210065 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 457px); position: relative; text-decoration: none; width: 50%; }",
	".framer-wZtKz .framer-vtwhsj { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: visible; padding: 40px 60px 40px 90px; position: relative; width: 1px; }",
	".framer-wZtKz .framer-1sh40gd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-wZtKz .framer-1gx1m1p, .framer-wZtKz .framer-1ktjtyo { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-wZtKz .framer-kkmvnx { flex: none; height: auto; max-width: 467px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-wZtKz .framer-upd07g-container { flex: none; height: auto; position: relative; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wZtKz .framer-14sto0w, .framer-wZtKz .framer-vtwhsj, .framer-wZtKz .framer-1sh40gd { gap: 0px; } .framer-wZtKz .framer-14sto0w > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-wZtKz .framer-14sto0w > :first-child { margin-left: 0px; } .framer-wZtKz .framer-14sto0w > :last-child { margin-right: 0px; } .framer-wZtKz .framer-vtwhsj > * { margin: 0px; margin-bottom: calc(30px / 2); margin-top: calc(30px / 2); } .framer-wZtKz .framer-vtwhsj > :first-child, .framer-wZtKz .framer-1sh40gd > :first-child { margin-top: 0px; } .framer-wZtKz .framer-vtwhsj > :last-child, .framer-wZtKz .framer-1sh40gd > :last-child { margin-bottom: 0px; } .framer-wZtKz .framer-1sh40gd > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	".framer-wZtKz.framer-v-1hbzd9b .framer-1atp1u3 { order: 1; }",
	".framer-wZtKz.framer-v-1hbzd9b .framer-vtwhsj { order: 0; }",
	".framer-wZtKz.framer-v-1hbzd9b .framer-kkmvnx { max-width: 470px; }",
	".framer-wZtKz.framer-v-1xmif2u .framer-14sto0w { flex-direction: column; width: 375px; }",
	".framer-wZtKz.framer-v-1xmif2u .framer-1atp1u3 { height: var(--framer-aspect-ratio-supported, 141px); width: 100%; }",
	".framer-wZtKz.framer-v-1xmif2u .framer-vtwhsj { flex: none; gap: 24px; padding: 30px 30px 30px 30px; width: 100%; }",
	".framer-wZtKz.framer-v-1xmif2u .framer-1sh40gd { gap: 14px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wZtKz.framer-v-1xmif2u .framer-14sto0w, .framer-wZtKz.framer-v-1xmif2u .framer-vtwhsj, .framer-wZtKz.framer-v-1xmif2u .framer-1sh40gd { gap: 0px; } .framer-wZtKz.framer-v-1xmif2u .framer-14sto0w > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-wZtKz.framer-v-1xmif2u .framer-14sto0w > :first-child, .framer-wZtKz.framer-v-1xmif2u .framer-vtwhsj > :first-child, .framer-wZtKz.framer-v-1xmif2u .framer-1sh40gd > :first-child { margin-top: 0px; } .framer-wZtKz.framer-v-1xmif2u .framer-14sto0w > :last-child, .framer-wZtKz.framer-v-1xmif2u .framer-vtwhsj > :last-child, .framer-wZtKz.framer-v-1xmif2u .framer-1sh40gd > :last-child { margin-bottom: 0px; } .framer-wZtKz.framer-v-1xmif2u .framer-vtwhsj > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-wZtKz.framer-v-1xmif2u .framer-1sh40gd > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } }",
	".framer-wZtKz.framer-v-12xm5bh .framer-14sto0w, .framer-wZtKz.framer-v-14ldy7r .framer-14sto0w { width: 768px; }",
	".framer-wZtKz.framer-v-12xm5bh .framer-1atp1u3 { height: var(--framer-aspect-ratio-supported, 141px); }",
	".framer-wZtKz.framer-v-12xm5bh .framer-vtwhsj { gap: 22px; padding: 40px 30px 40px 40px; }",
	".framer-wZtKz.framer-v-12xm5bh .framer-1sh40gd, .framer-wZtKz.framer-v-14ldy7r .framer-1sh40gd { gap: 13px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wZtKz.framer-v-12xm5bh .framer-vtwhsj, .framer-wZtKz.framer-v-12xm5bh .framer-1sh40gd { gap: 0px; } .framer-wZtKz.framer-v-12xm5bh .framer-vtwhsj > * { margin: 0px; margin-bottom: calc(22px / 2); margin-top: calc(22px / 2); } .framer-wZtKz.framer-v-12xm5bh .framer-vtwhsj > :first-child, .framer-wZtKz.framer-v-12xm5bh .framer-1sh40gd > :first-child { margin-top: 0px; } .framer-wZtKz.framer-v-12xm5bh .framer-vtwhsj > :last-child, .framer-wZtKz.framer-v-12xm5bh .framer-1sh40gd > :last-child { margin-bottom: 0px; } .framer-wZtKz.framer-v-12xm5bh .framer-1sh40gd > * { margin: 0px; margin-bottom: calc(13px / 2); margin-top: calc(13px / 2); } }",
	".framer-wZtKz.framer-v-14ldy7r .framer-1atp1u3 { height: var(--framer-aspect-ratio-supported, 141px); order: 1; }",
	".framer-wZtKz.framer-v-14ldy7r .framer-vtwhsj { gap: 22px; order: 0; padding: 40px 40px 40px 30px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wZtKz.framer-v-14ldy7r .framer-vtwhsj, .framer-wZtKz.framer-v-14ldy7r .framer-1sh40gd { gap: 0px; } .framer-wZtKz.framer-v-14ldy7r .framer-vtwhsj > * { margin: 0px; margin-bottom: calc(22px / 2); margin-top: calc(22px / 2); } .framer-wZtKz.framer-v-14ldy7r .framer-vtwhsj > :first-child, .framer-wZtKz.framer-v-14ldy7r .framer-1sh40gd > :first-child { margin-top: 0px; } .framer-wZtKz.framer-v-14ldy7r .framer-vtwhsj > :last-child, .framer-wZtKz.framer-v-14ldy7r .framer-1sh40gd > :last-child { margin-bottom: 0px; } .framer-wZtKz.framer-v-14ldy7r .framer-1sh40gd > * { margin: 0px; margin-bottom: calc(13px / 2); margin-top: calc(13px / 2); } }",
	...css2,
	...css,
	...css3,
	...css4,
];
var FramercmakoftLV = withCSS(Component, css5, "framer-wZtKz");
var stdin_default2 = FramercmakoftLV;
FramercmakoftLV.displayName = "Service Widget";
FramercmakoftLV.defaultProps = {
	height: 457,
	width: 1296,
};
addPropertyControls(FramercmakoftLV, {
	variant: {
		options: ["VwMacgI9x", "hzdq50srG", "J0h__7E7k", "K11kyKdzf", "xupnY_m5T"],
		optionTitles: [
			"Default",
			"Variant 2",
			"Phone",
			"Tablet",
			"Variant 2 Tablet",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	oCYyIcKiB: {
		__defaultAssetReference:
			"data:framer/asset-reference,hZfpzM20KHHp6sze1i5OJ1Jrww.jpg?originalFilename=Bg.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	Nk6Fi3exM: {
		defaultValue: "BEST FOOD",
		displayTextArea: false,
		title: "Subtitle",
		type: ControlType.String,
	},
	ibAcBR7vA: {
		defaultValue: "The Restaurant",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	buCnMsH9E: {
		defaultValue:
			"Well-trained restaurant staff collaborate harmoniously to orchestrate these elements, culminating in a memorable and satisfying dining venture.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	JVofx01uU: {
		title: "Link",
		type: ControlType.Link,
	},
	CIgwIieY3: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(FramercmakoftLV, [
	...ButtonFonts,
	...fonts2,
	...fonts,
	...fonts3,
	...fonts4,
]);

// virtual:service-widget
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceWidgetFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var service_widget_default = ComponentWithRoot;
export { service_widget_default as default };
