// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Center' // Variant
 * title ?: string // Title 
 * text?: string // Text
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-CL76FT5C.js";
import { className, css, fonts } from "./chunks/chunk-JXJCIQWW.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:service-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zWuEhcnoD3zL3UMV7IRt/2d0quWUvH2rel6msW23H/eX7OPV99f.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["FpM6wu_vz", "t9BDV8xDI"];
var serializationHash = "framer-cTgBE";
var variantClassNames = {
	FpM6wu_vz: "framer-v-17w5977",
	t9BDV8xDI: "framer-v-1ynyh4i",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Center: "t9BDV8xDI",
	Default: "FpM6wu_vz",
};
var getProps = ({ height, id, text, title, width, ...props }) => {
	return {
		...props,
		f7V_pTQYv:
			text ??
			props.f7V_pTQYv ??
			"With our service you may enjoy the finest life in our resort.",
		mBSkyvezY: title ?? props.mBSkyvezY ?? "High Speed Wifi",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "FpM6wu_vz",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		mBSkyvezY: mBSkyvezY2,
		f7V_pTQYv: f7V_pTQYv2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "FpM6wu_vz",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17w5977",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"FpM6wu_vz"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								t9BDV8xDI: {
									"data-framer-name": "Center",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-15eb194"}
							data-framer-name={"Service Card Body"}
							layoutDependency={layoutDependency}
							layoutId={"Qt0xdBsui"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-fqiy8f"}
								data-framer-name={"Service Card Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"MT1GLrMp2"}
								style={{
									"--extracted-1eung3n":
										"var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27))",
								}}
								text={mBSkyvezY2}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										t9BDV8xDI: {
											children: (
												<React.Fragment>
													<motion.h4
														className={"framer-styles-preset-m5v4m7"}
														data-styles-preset={"r8yG0RPK0"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-1eung3n, var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)))",
														}}
													>
														{"High Speed Wifi"}
													</motion.h4>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-m5v4m7"}
										data-styles-preset={"r8yG0RPK0"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27)))",
										}}
									>
										{"High Speed Wifi"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-uvp7v3"}
								data-framer-name={"Service Card Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"rwcgdr5Rh"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56))",
								}}
								text={f7V_pTQYv2}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										t9BDV8xDI: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1wngm1p"}
														data-styles-preset={"BSuZ5tUoG"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)))",
														}}
													>
														{
															"With our service you may enjoy the finest life in our resort."
														}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1wngm1p"}
										data-styles-preset={"BSuZ5tUoG"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56)))",
										}}
									>
										{
											"With our service you may enjoy the finest life in our resort."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-cTgBE.framer-zpal9i, .framer-cTgBE .framer-zpal9i { display: block; }",
	".framer-cTgBE.framer-17w5977 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 220px; justify-content: flex-start; overflow: visible; padding: 34px 30px 34px 30px; position: relative; width: 416px; }",
	".framer-cTgBE .framer-15eb194 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-cTgBE .framer-fqiy8f { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-cTgBE .framer-uvp7v3 { flex: none; height: auto; max-width: 290px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-cTgBE.framer-v-1ynyh4i.framer-17w5977 { align-content: center; align-items: center; gap: 22px; justify-content: center; padding: 30px; }",
	".framer-cTgBE.framer-v-1ynyh4i .framer-15eb194 { gap: 15px; }",
	".framer-cTgBE.framer-v-1ynyh4i .framer-uvp7v3 { max-width: unset; }",
	...css2,
	...css,
	'.framer-cTgBE[data-border="true"]::after, .framer-cTgBE [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramereX7OPV99f = withCSS(Component, css3, "framer-cTgBE");
var stdin_default = FramereX7OPV99f;
FramereX7OPV99f.displayName = "Service Card";
FramereX7OPV99f.defaultProps = {
	height: 220,
	width: 416,
};
addPropertyControls(FramereX7OPV99f, {
	variant: {
		options: ["FpM6wu_vz", "t9BDV8xDI"],
		optionTitles: ["Default", "Center"],
		title: "Variant",
		type: ControlType.Enum,
	},
	mBSkyvezY: {
		defaultValue: "High Speed Wifi",
		displayTextArea: false,
		title: "Title ",
		type: ControlType.String,
	},
	f7V_pTQYv: {
		defaultValue:
			"With our service you may enjoy the finest life in our resort.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramereX7OPV99f,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:service-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "t9BDV8xDI",
	xl: "FpM6wu_vz",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var service_card_default = ComponentWithRoot;
export { service_card_default as default };
