// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:star
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zDom4XK5jNWyOIazigq0/S8dDfx3VoCEuyYn3DPWN/om9OfPKGW.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	SVG,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["l9PoYKlNQ"];
var variantClassNames = {
	l9PoYKlNQ: "framer-v-ij1761",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "l9PoYKlNQ",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-DW6Bc", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-ij1761", className)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"l9PoYKlNQ"}
						ref={ref}
						style={{
							...style,
						}}
					>
						<SVG
							className={"framer-1bbdwic"}
							data-framer-name={"Star "}
							fill={"rgba(0,0,0,1)"}
							intrinsicHeight={25}
							intrinsicWidth={25}
							layoutDependency={layoutDependency}
							layoutId={"zCU47frmA"}
							svg={
								'<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M11.3583 2.56133C11.7987 1.57322 13.2013 1.57321 13.6417 2.56132L15.6597 7.08852C15.8414 7.49606 16.2265 7.77587 16.6702 7.8227L21.5994 8.34295C22.6753 8.4565 23.1087 9.79037 22.3051 10.5146L18.623 13.8328C18.2916 14.1315 18.1445 14.5843 18.237 15.0207L19.2655 19.8695C19.4899 20.9278 18.3553 21.7521 17.4181 21.2116L13.1245 18.7352C12.738 18.5123 12.262 18.5123 11.8755 18.7352L7.58185 21.2116C6.64473 21.7521 5.51006 20.9278 5.73453 19.8695L6.76295 15.0207C6.85553 14.5843 6.70843 14.1315 6.37697 13.8328L2.69495 10.5146C1.89131 9.79038 2.32471 8.4565 3.40056 8.34295L8.32978 7.8227C8.77351 7.77587 9.15863 7.49606 9.34029 7.08852L11.3583 2.56133Z" fill="#E4A853"/>\n</svg>\n'
							}
							withExternalLayout={true}
						/>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-DW6Bc [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-DW6Bc .framer-uh7tnb { display: block; }",
	".framer-DW6Bc .framer-ij1761 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 25px; }",
	".framer-DW6Bc .framer-1bbdwic { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 25px); position: relative; width: 25px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-DW6Bc .framer-ij1761 { gap: 0px; } .framer-DW6Bc .framer-ij1761 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-DW6Bc .framer-ij1761 > :first-child { margin-left: 0px; } .framer-DW6Bc .framer-ij1761 > :last-child { margin-right: 0px; } }",
];
var Framerom9OfPKGW = withCSS(Component, css, "framer-DW6Bc");
var stdin_default = Framerom9OfPKGW;
Framerom9OfPKGW.displayName = "Star";
Framerom9OfPKGW.defaultProps = {
	height: 25,
	width: 25,
};
addFonts(Framerom9OfPKGW, []);

// virtual:star
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var star_default = ComponentWithRoot;
export { star_default as default };
