// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 630e38d9bc1c5de2 "Fjellheimen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * userName?: string // User Name
 * userPosition?: string // User Position
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-WXRG7P7E.js";
import { className, css, fonts } from "./chunks/chunk-DQ7NIFUT.js";
import { routes } from "./chunks/chunk-OPAGGL3D.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2EI35t6Ts38iQqB8dN2d/TxfKsZDzkm95yeKZUYpT/BQ1rsA3_L.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	RichText,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["uoFTAz1bH"];
var variantClassNames = {
	uoFTAz1bH: "framer-v-1ovdj67",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({
	height,
	id,
	image,
	userName,
	userPosition,
	width,
	...props
}) => {
	var ref, ref1, ref2;
	return {
		...props,
		D0VaPe59K:
			(ref =
				userName !== null && userName !== void 0
					? userName
					: props.D0VaPe59K) !== null && ref !== void 0
				? ref
				: "Kimberly Hansen",
		kgK46Q4cb:
			(ref1 = image !== null && image !== void 0 ? image : props.kgK46Q4cb) !==
				null && ref1 !== void 0
				? ref1
				: {
						src: new URL(
							"assets/1024/viGDlmAnjVCfZLIXLPjwmM8KWU.png",
							"https://framerusercontent.com/modules/2EI35t6Ts38iQqB8dN2d/TxfKsZDzkm95yeKZUYpT/BQ1rsA3_L.js",
						).href,
						srcSet: `${new URL("assets/512/viGDlmAnjVCfZLIXLPjwmM8KWU.png", "https://framerusercontent.com/modules/2EI35t6Ts38iQqB8dN2d/TxfKsZDzkm95yeKZUYpT/BQ1rsA3_L.js").href} 512w, ${new URL("assets/1024/viGDlmAnjVCfZLIXLPjwmM8KWU.png", "https://framerusercontent.com/modules/2EI35t6Ts38iQqB8dN2d/TxfKsZDzkm95yeKZUYpT/BQ1rsA3_L.js").href} 1024w, ${new URL("assets/viGDlmAnjVCfZLIXLPjwmM8KWU.png", "https://framerusercontent.com/modules/2EI35t6Ts38iQqB8dN2d/TxfKsZDzkm95yeKZUYpT/BQ1rsA3_L.js").href} 1976w`,
					},
		pbMbXQOMb:
			(ref2 =
				userPosition !== null && userPosition !== void 0
					? userPosition
					: props.pbMbXQOMb) !== null && ref2 !== void 0
				? ref2
				: "Junior Manager",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		D0VaPe59K,
		pbMbXQOMb,
		kgK46Q4cb,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uoFTAz1bH",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-tg1Ya", className2, className, classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-1ovdj67", className3)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"uoFTAz1bH"}
						ref={ref}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								'var(--token-57644229-9aea-4671-a3e2-529f7b58afe0, rgb(221, 217, 214)) /* {"name":"Neutral / 03"} */',
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-a7f7ae5f-a181-442b-8823-be0ca1b170fe, rgb(255, 255, 255))",
							...style,
						}}
					>
						<motion.div
							className={"framer-1xp171"}
							data-framer-name={"Team Card Image"}
							layoutDependency={layoutDependency}
							layoutId={"iIbQqZXoK"}
						>
							<Image
								background={{
									alt: "",
									fit: "stretch",
									sizes: "min(416px, 100vw)",
									...toResponsiveImage(kgK46Q4cb),
								}}
								className={"framer-h4sw17"}
								data-framer-name={"Team Image"}
								layoutDependency={layoutDependency}
								layoutId={"kWXv_E1WI"}
							/>
							<motion.div
								className={"framer-11voy76"}
								data-framer-name={"Background"}
								layoutDependency={layoutDependency}
								layoutId={"UAsigCMpk"}
								style={{
									backgroundColor: "rgb(221, 217, 213)",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1fiex7o"}
							data-framer-name={"User Info Block"}
							layoutDependency={layoutDependency}
							layoutId={"NrjkYFcJM"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-6iqf2k"}
								data-framer-name={"User Name"}
								layoutDependency={layoutDependency}
								layoutId={"ZLIStTPTU"}
								style={{
									"--extracted-1eung3n":
										"var(--token-0c8fd507-faea-491a-8caf-ad6cd40c959b, rgb(27, 27, 27))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={D0VaPe59K}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-m5v4m7"}
										data-styles-preset={"r8yG0RPK0"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color": "var(--extracted-1eung3n)",
										}}
									>
										{"Kimberly Hansen"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-hhivoq"}
								data-framer-name={"User Position"}
								layoutDependency={layoutDependency}
								layoutId={"zt8PdWorE"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6d05c7e7-3db1-411c-8b7a-d2c7f93bf6a9, rgb(61, 58, 56))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={pbMbXQOMb}
								verticalAlignment={"center"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1sb8f1f"}
										data-styles-preset={"Clb2Z6A0U"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color": "var(--extracted-r6o4lv)",
										}}
									>
										{"Junior Manager"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css3 = [
	'.framer-tg1Ya [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-tg1Ya .framer-16ejlaf { display: block; }",
	".framer-tg1Ya .framer-1ovdj67 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 416px; }",
	".framer-tg1Ya .framer-1xp171 { align-content: center; align-items: center; aspect-ratio: 1.04 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 400px); justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-tg1Ya .framer-h4sw17 { aspect-ratio: 1.04 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 400px); position: relative; width: 100%; z-index: 2; }",
	".framer-tg1Ya .framer-11voy76 { flex: none; height: 100%; left: 0px; position: absolute; top: 0px; width: 100%; z-index: 1; }",
	".framer-tg1Ya .framer-1fiex7o { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: visible; padding: 30px 30px 30px 30px; position: relative; width: 100%; }",
	".framer-tg1Ya .framer-6iqf2k, .framer-tg1Ya .framer-hhivoq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-tg1Ya .framer-1ovdj67, .framer-tg1Ya .framer-1xp171, .framer-tg1Ya .framer-1fiex7o { gap: 0px; } .framer-tg1Ya .framer-1ovdj67 > *, .framer-tg1Ya .framer-1xp171 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-tg1Ya .framer-1ovdj67 > :first-child, .framer-tg1Ya .framer-1xp171 > :first-child, .framer-tg1Ya .framer-1fiex7o > :first-child { margin-top: 0px; } .framer-tg1Ya .framer-1ovdj67 > :last-child, .framer-tg1Ya .framer-1xp171 > :last-child, .framer-tg1Ya .framer-1fiex7o > :last-child { margin-bottom: 0px; } .framer-tg1Ya .framer-1fiex7o > * { margin: 0px; margin-bottom: calc(5px / 2); margin-top: calc(5px / 2); } }",
	...css2,
	...css,
];
var FramerBQ1rsA3_L = withCSS(Component, css3, "framer-tg1Ya");
var stdin_default = FramerBQ1rsA3_L;
FramerBQ1rsA3_L.displayName = "Team Card";
FramerBQ1rsA3_L.defaultProps = {
	height: 523,
	width: 416,
};
addPropertyControls(FramerBQ1rsA3_L, {
	D0VaPe59K: {
		defaultValue: "Kimberly Hansen",
		displayTextArea: false,
		title: "User Name",
		type: ControlType.String,
	},
	pbMbXQOMb: {
		defaultValue: "Junior Manager",
		displayTextArea: false,
		title: "User Position",
		type: ControlType.String,
	},
	kgK46Q4cb: {
		__defaultAssetReference:
			"data:framer/asset-reference,viGDlmAnjVCfZLIXLPjwmM8KWU.png?originalFilename=Image.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(FramerBQ1rsA3_L, [...fonts2, ...fonts]);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"630e38d9bc1c5de2480ff89f40f250287508922fc0f68cbf1da206c1e6a09322"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
